import JSZip from 'jszip'
import { cellHash, connectedWallSprite, createEmptyBundle, getContentBounds, LABEL_FONTS, LABEL_SIZES, LINE_STYLES, OBJECTS, resolveLabelColor, SCHEMA_VERSION, setTerrainCell, setTerrainStyle, TERRAIN, terrainEntries, terrainRenderEntries, terrainStyleAt, uuid } from '../constants.js'
import { saveProjectBundle } from './db.js'
import { roomShapePoints, strokeFalloffLayers, strokeSoftness } from './mapGeometry.js'
import { loadTerrainMaterialSources, renderTerrainRegion } from './terrainRenderer.js'

const safeName=(value)=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'map'
function download(blob,name){const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export async function exportMapArchive(bundle){const zip=new JSZip();zip.file('manifest.json',JSON.stringify({format:'story-shack-observatory',schemaVersion:SCHEMA_VERSION,exportedAt:new Date().toISOString(),bundle},null,2));download(await zip.generateAsync({type:'blob',compression:'DEFLATE'}),`${safeName(bundle.project.title)}.observatory`)}
export async function importMap(file){const zip=await JSZip.loadAsync(file),entry=zip.file('manifest.json');if(!entry)throw new Error('This map archive has no manifest.');const manifest=JSON.parse(await entry.async('text'));if(manifest.format!=='story-shack-observatory'||![2,3,4,5].includes(manifest.schemaVersion))throw new Error('This map archive version is not supported.');const source=manifest.bundle,copy=createEmptyBundle({title:source.project.title,description:source.project.description,mapType:source.project.mapType});for(const {x,y,terrain} of terrainEntries(source)){setTerrainCell(copy,x,y,terrain);setTerrainStyle(copy,x,y,terrainStyleAt(source,x,y))}copy.terrainStrokes=(source.terrainStrokes||[]).map((item)=>({...item,id:uuid(),projectId:copy.project.id,layerId:copy.layers.find((layer)=>layer.kind==='terrain').id}));copy.structures=(source.structures||[]).map((item)=>({...item,id:uuid(),projectId:copy.project.id,layerId:copy.layers.find((layer)=>layer.kind==='structure').id}));copy.objects=(source.objects||[]).map((item)=>({...item,id:uuid(),projectId:copy.project.id,layerId:copy.layers.find((layer)=>layer.kind==='objects').id}));copy.labels=(source.labels||[]).map((item)=>({...item,id:uuid(),projectId:copy.project.id,layerId:copy.layers.find((layer)=>layer.kind==='labels').id}));await saveProjectBundle(copy);return copy.project}
const loadImage=(src)=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=src})
const drawSprite=(context,image,sprite,x,y,size)=>{const sw=image.naturalWidth/4,sh=image.naturalHeight/4;context.drawImage(image,(sprite%4)*sw,Math.floor(sprite/4)*sh,sw,sh,x,y,size,size)}
const mapPoint=(point,bounds,size)=>({x:(point.x-bounds.minX)*size,y:(point.y-bounds.minY)*size})
function tracePath(context,points,bounds,size,closed=false){if(!points?.length)return;const first=mapPoint(points[0],bounds,size);context.beginPath();context.moveTo(first.x,first.y);for(const point of points.slice(1)){const next=mapPoint(point,bounds,size);context.lineTo(next.x,next.y)}if(closed)context.closePath()}
function materialPattern(context,source,period,size){const pattern=context.createPattern(source,'repeat');if(pattern?.setTransform)pattern.setTransform(new DOMMatrix().scale(period*size/source.width,period*size/source.height));return pattern}
function samplePath(points,spacing,visit){let carry=0;for(let index=1;index<points.length;index++){const from=points[index-1],to=points[index],dx=to.x-from.x,dy=to.y-from.y,length=Math.hypot(dx,dy);if(!length)continue;for(let distance=spacing-carry;distance<=length;distance+=spacing){const amount=distance/length;visit({x:from.x+dx*amount,y:from.y+dy*amount},dx/length,dy/length)}carry=(carry+length)%spacing}}
function drawContinuousStrokeLayer(context,stroke,bounds,size,patterns,radiusScale=1,alpha=1){
  if(!stroke.points?.length)return
  const radius=Math.max(.08,stroke.radius||.5)*size*radiusScale
  context.save();context.globalAlpha=alpha;context.fillStyle=context.strokeStyle=stroke.mode==='erase'?'#20231e':patterns[stroke.terrain]||'#6c6556';context.lineCap='round';context.lineJoin='round'
  if(stroke.discrete){for(const point of stroke.points){const next=mapPoint(point,bounds,size);context.beginPath();if(stroke.edge==='crisp')context.rect(next.x-radius,next.y-radius,radius*2,radius*2);else context.arc(next.x,next.y,radius,0,Math.PI*2);context.fill()}}
  else if(stroke.points.length===1){const next=mapPoint(stroke.points[0],bounds,size);context.beginPath();context.arc(next.x,next.y,radius,0,Math.PI*2);context.fill()}
  else{tracePath(context,stroke.points,bounds,size);context.lineWidth=radius*2;context.stroke()}
  context.restore()
}
function drawContinuousStroke(context,stroke,bounds,size,patterns){
  const softness=strokeSoftness(stroke)
  if(softness<=.02){drawContinuousStrokeLayer(context,stroke,bounds,size,patterns);return}
  for(const layer of strokeFalloffLayers(1,softness))drawContinuousStrokeLayer(context,stroke,bounds,size,patterns,layer.radius,layer.alpha)
}
function drawVectorWall(context,item,bounds,size,lineImages,closed=false){
  const points=closed?[...item.points,item.points[0]]:item.points;if(!points?.length)return
  const style=item.lineStyle||'stone-wall',width=item.wallWidth||.52,image=lineImages[style]||lineImages['stone-wall'],spacing=Math.max(.12,width*.34),stamp=(point,dx=1,dy=0)=>{if(!image)return;const next=mapPoint(point,bounds,size),count=12,sourceWidth=image.naturalWidth/count,index=cellHash(Math.round(point.x*19),Math.round(point.y*23))%count;context.save();context.translate(next.x,next.y);context.rotate(Math.atan2(dy,dx));context.drawImage(image,index*sourceWidth,0,sourceWidth,image.naturalHeight,-spacing*size*.66,-width*size/2,spacing*size*1.32,width*size);context.restore()}
  if(points.length===1)stamp(points[0]);else{const first=points[0],second=points[1];stamp(first,second.x-first.x,second.y-first.y);samplePath(points,spacing,stamp);const last=points.at(-1),previous=points.at(-2);stamp(last,last.x-previous.x,last.y-previous.y)}
}
function wrappedLabelLines(context,text,maxWidth){const lines=[];for(const paragraph of String(text).split('\n')){const words=paragraph.split(/\s+/).filter(Boolean);if(!words.length){lines.push('');continue}let line=words.shift();for(const word of words){const candidate=`${line} ${word}`;if(context.measureText(candidate).width<=maxWidth)line=candidate;else{lines.push(line);line=word}}lines.push(line)}return lines}
export async function exportMapPng(bundle){
  const bounds=getContentBounds(bundle,1),baseSize=bundle.project.cellSize||40,maxPixels=8192,scale=Math.min(1,maxPixels/(Math.max(bounds.width,bounds.height)*baseSize)),size=baseSize*scale
  const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bounds.width*size));canvas.height=Math.max(1,Math.round(bounds.height*size));const context=canvas.getContext('2d')
  context.fillStyle='#20231e';context.fillRect(0,0,canvas.width,canvas.height)
  const usedTerrainIds=new Set(terrainRenderEntries(bundle).map((cell)=>cell.terrain));for(const stroke of bundle.terrainStrokes||[])if(!stroke.deletedAt&&stroke.terrain)usedTerrainIds.add(stroke.terrain);for(const structure of bundle.structures||[])if(!structure.deletedAt){if(structure.floorTerrain)usedTerrainIds.add(structure.floorTerrain);if(structure.wallTerrain)usedTerrainIds.add(structure.wallTerrain)}
  const [wallAtlas,objectAtlas,materialSources,...lineAtlases]=await Promise.all([loadImage('/assets/terrain/connected-walls-atlas.webp'),loadImage('/assets/objects/story-shack-object-atlas.webp'),loadTerrainMaterialSources([...usedTerrainIds]),...LINE_STYLES.map((style)=>loadImage(style.asset))]),objectById=Object.fromEntries(OBJECTS.map((item)=>[item.id,item])),lineImages=Object.fromEntries(LINE_STYLES.map((style,index)=>[style.id,lineAtlases[index]]))
  const px=(value,min)=>Math.round((value-min)*size)
  await renderTerrainRegion(context,{cells:terrainRenderEntries(bundle),originX:bounds.minX,originY:bounds.minY,cellSize:size,clearWidth:canvas.width,clearHeight:canvas.height,clear:false})
  const patterns=Object.fromEntries(TERRAIN.filter((terrain)=>materialSources[terrain.id]).map((terrain)=>[terrain.id,materialPattern(context,materialSources[terrain.id],terrain.texturePeriod||16,size)]))
  for(const stroke of bundle.terrainStrokes||[])if(!stroke.deletedAt)drawContinuousStroke(context,stroke,bounds,size,patterns)
  const legacyWalls=(bundle.structures||[]).filter((entry)=>!entry.deletedAt&&entry.kind==='wall')
  for(const item of legacyWalls)drawSprite(context,wallAtlas,connectedWallSprite(legacyWalls,item),px(item.x,bounds.minX),px(item.y,bounds.minY),Math.ceil(size))
  const vectorStructures=(bundle.structures||[]).filter((entry)=>!entry.deletedAt&&['room','wall-path'].includes(entry.kind)).sort((first,second)=>(first.zIndex||0)-(second.zIndex||0))
  for(const item of vectorStructures)if(item.kind==='room'){const points=roomShapePoints(item);tracePath(context,points,bounds,size,true);context.fillStyle=patterns[item.floorTerrain||'stone'];context.fill();drawVectorWall(context,{...item,points},bounds,size,lineImages,true)}else drawVectorWall(context,item,bounds,size,lineImages,false)
  for(const item of (bundle.objects||[]).filter((entry)=>!entry.deletedAt)){const asset=objectById[item.assetId];if(!asset)continue;const renderSize=Math.max(asset.width,asset.height)*size;context.save();context.translate(px(item.x,bounds.minX)+size/2,px(item.y,bounds.minY)+size/2);context.rotate((item.rotation||0)*Math.PI/180);context.scale(item.scale||1,item.scale||1);drawSprite(context,objectAtlas,asset.sprite,-renderSize/2,-renderSize/2,renderSize);context.restore()}
  context.textAlign='center';context.textBaseline='middle';for(const item of (bundle.labels||[]).filter((entry)=>!entry.deletedAt)){const labelSize=LABEL_SIZES.find(({id})=>id===item.size)||LABEL_SIZES[1],font=LABEL_FONTS.find(({id})=>id===item.font)||LABEL_FONTS[0],color=resolveLabelColor(item.color),fontSize=(item.fontSize||labelSize.sceneSize)*size;context.font=`${item.bold||item.size==='large'?700:600} ${fontSize}px ${font.family}, sans-serif`;context.fillStyle=color.value;const boxed=Number.isFinite(item.boxWidth),boxWidth=(boxed?item.boxWidth:1)*size,boxHeight=(boxed?(item.boxHeight||2.25):1)*size,centerX=px(item.x,bounds.minX)+boxWidth/2,centerY=px(item.y,bounds.minY)+boxHeight/2,lines=boxed?wrappedLabelLines(context,item.text,boxWidth):[item.text],lineHeight=fontSize*1.2,startY=boxed?-boxHeight/2+fontSize*.65:0;context.save();context.translate(centerX,centerY);context.rotate((item.rotation||0)*Math.PI/180);for(const [index,line]of lines.entries())context.fillText(line,0,startY+index*lineHeight);context.restore()}
  const blob=await new Promise((resolve)=>canvas.toBlob(resolve,'image/png'));download(blob,`${safeName(bundle.project.title)}.png`)
}
export function exportMapNotes(bundle){const bounds=getContentBounds(bundle);const lines=[`# ${bundle.project.title}`,'',bundle.project.description,'','## Map details',`- Type: ${bundle.project.mapType}`,`- Content bounds: (${bounds.minX}, ${bounds.minY}) to (${bounds.maxX}, ${bounds.maxY})`,'','## Labels',...(bundle.labels||[]).filter((item)=>!item.deletedAt).map((item)=>`- ${item.text} (${item.x}, ${item.y})`)];download(new Blob([lines.join('\n')],{type:'text/markdown'}),`${safeName(bundle.project.title)}.md`)}
