import JSZip from 'jszip'
import domtoimage from 'dom-to-image-more'
import { createEmptyBundle, uuid } from '../constants.js'
import { saveProjectBundle } from './db.js'

const safeName=(value)=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'map'
function download(blob,name){const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export async function exportMapArchive(bundle){const zip=new JSZip();zip.file('manifest.json',JSON.stringify({format:'story-shack-mapworks',schemaVersion:2,exportedAt:new Date().toISOString(),bundle},null,2));download(await zip.generateAsync({type:'blob',compression:'DEFLATE'}),`${safeName(bundle.project.title)}.mapworks`)}
export async function importMap(file){const zip=await JSZip.loadAsync(file),entry=zip.file('manifest.json');if(!entry)throw new Error('This map archive has no manifest.');const manifest=JSON.parse(await entry.async('text'));if(manifest.format!=='story-shack-mapworks'||manifest.schemaVersion!==2)throw new Error('This map archive version is not supported.');const source=manifest.bundle,copy=createEmptyBundle({title:source.project.title,description:source.project.description,mapType:source.project.mapType,width:source.project.width,height:source.project.height});copy.chunks[0].cells=[...source.chunks[0].cells];copy.structures=(source.structures||[]).map((item)=>({...item,id:uuid(),projectId:copy.project.id,layerId:copy.layers.find((layer)=>layer.kind==='structure').id}));copy.objects=(source.objects||[]).map((item)=>({...item,id:uuid(),projectId:copy.project.id,layerId:copy.layers.find((layer)=>layer.kind==='objects').id}));copy.labels=(source.labels||[]).map((item)=>({...item,id:uuid(),projectId:copy.project.id,layerId:copy.layers.find((layer)=>layer.kind==='labels').id}));await saveProjectBundle(copy);return copy.project}
export async function exportMapPng(element,bundle){download(await domtoimage.toBlob(element,{bgcolor:'#191a18',width:bundle.project.width*bundle.project.cellSize,height:bundle.project.height*bundle.project.cellSize}),`${safeName(bundle.project.title)}.png`)}
export function exportMapNotes(bundle){const lines=[`# ${bundle.project.title}`,'',bundle.project.description,'','## Map details',`- Type: ${bundle.project.mapType}`,`- Size: ${bundle.project.width} × ${bundle.project.height} tiles`,'','## Labels',...(bundle.labels||[]).filter((item)=>!item.deletedAt).map((item)=>`- ${item.text} (${item.x}, ${item.y})${item.hidden?' — hidden':''}`)];download(new Blob([lines.join('\n')],{type:'text/markdown'}),`${safeName(bundle.project.title)}.md`)}
