import { watch } from 'vue'
import { LABEL_COLORS, LABEL_FONTS, LABEL_SIZES, LINE_STYLES, OBJECTS, TERRAIN, nowIso, terrainAt, WORLD_COORDINATE_LIMIT } from '../constants.js'
import { exportMapArchive, exportMapNotes, exportMapPng } from './portability.js'
import { roomShapePoints, terrainAtPoint } from './mapGeometry.js'
import { codedError, disposeScope, ensureRevision, operations, OUTPUT_LIMIT, previews, registerScope, result, runTool, stable, supported, tool } from './webMcpRuntime.js'

const base = { type: 'object', additionalProperties: false }
const uuidSchema = { type: 'string', format: 'uuid' }
const text = (max = 2000) => ({ type: 'string', maxLength: max })
const coordinate = { type: 'number', minimum: -WORLD_COORDINATE_LIMIT, maximum: WORLD_COORDINATE_LIMIT }
const gridCoordinate = { type: 'integer', minimum: -WORLD_COORDINATE_LIMIT, maximum: WORLD_COORDINATE_LIMIT }
const pointSchema = { ...base, properties: { x: coordinate, y: coordinate }, required: ['x', 'y'] }
const pointsSchema = (maximum = 500) => ({ type: 'array', minItems: 1, maxItems: maximum, items: pointSchema })
const linePointsSchema = (maximum = 500) => ({ type: 'array', minItems: 2, maxItems: maximum, items: pointSchema })
const cellsSchema = { type: 'array', minItems: 1, maxItems: 500, items: { ...base, properties: { x: gridCoordinate, y: gridCoordinate }, required: ['x', 'y'] } }
const operation = { operation_id: uuidSchema, expected_revision: { type: 'integer', minimum: 1 } }
const riskSchema = { type: 'object', additionalProperties: false, properties: { preview: { type: 'boolean' }, preview_token: { type: 'string', maxLength: 100 } }, required: ['preview'] }
const mutation = (properties, required = []) => ({ ...base, properties: { ...operation, ...properties, risk: riskSchema }, required: ['operation_id', 'expected_revision', ...required] })
const mapManagementMutation = (properties, required = []) => ({ ...base, properties: { operation_id: uuidSchema, expected_revision: { type: 'integer', minimum: 0 }, ...properties }, required: ['operation_id', 'expected_revision', ...required] })
const terrainIds = TERRAIN.map(({ id }) => id), objectIds = OBJECTS.map(({ id }) => id), lineStyleIds = LINE_STYLES.map(({ id }) => id)
const labelSizeIds = LABEL_SIZES.map(({ id }) => id), labelFontIds = LABEL_FONTS.map(({ id }) => id), labelColorIds = LABEL_COLORS.map(({ id }) => id)
const layerKinds = ['terrain', 'structure', 'objects', 'labels'], shapeTypes = ['rectangle', 'ellipse', 'polygon', 'star']
const labelColorSchema = { anyOf: [{ enum: labelColorIds }, { type: 'string', pattern: '^#[0-9A-Fa-f]{6}$' }] }
const labelTextSchema = { type: 'string', minLength: 1, maxLength: 200 }
const terrainEdgeSchema = { enum: ['crisp', 'natural', 'wild'], description: 'Edge character. Prefer natural or wild for organic geography; use crisp for deliberate constructed boundaries.' }
const terrainSoftnessSchema = { type: 'integer', minimum: 0, maximum: 100, default: 100, description: 'Edge blend percentage. Prefer 65-100 for coastlines and other organic terrain; reserve 0-40 for roads, masonry, excavated ground, and intentional hard boundaries.' }
const eraseSoftnessSchema = { type: 'integer', minimum: 0, maximum: 100, default: 0, description: 'Erase-edge blend percentage. Raise toward 65-100 for natural erosion; keep 0-40 for deliberate hard cutouts.' }

const PROJECT_TOOL_NAMES = ['get_map_context', 'get_map_asset_catalog', 'paint_map_regions', 'paint_map_strokes', 'erase_map_terrain', 'create_map_shapes', 'draw_map_lines', 'place_map_objects', 'add_map_labels', 'update_map_elements', 'set_map_layer_visibility', 'change_map_history', 'delete_map_elements', 'export_map']

function libraryTools(store) { return [
  tool('get_observatory_capabilities', 'Describe Observatory', 'Learn the stable local mapmaking contract, limits, coordinate system, and available map tools.', base, async () => result('ok', 'get_observatory_capabilities', 'Observatory is ready for local mapmaking.', {
    storage: 'local IndexedDB; no cloud account or remote map service', canvas: { type: 'endless signed-coordinate grid', coordinate_limit: WORLD_COORDINATE_LIMIT }, map_types: ['dungeon', 'village', 'interior', 'wilderness', 'world'],
    creation: ['terrain regions', 'continuous terrain strokes', 'terrain erasing', 'editable shapes', 'styled lines', 'semantic objects', 'styled text boxes'], modification: ['inspect elements by stable ID', 'move, resize, rotate and restyle elements', 'replace line geometry', 'toggle layers', 'undo and redo'],
    visual_guidance: {
      natural_terrain: 'Build organic geography with overlapping, offset strokes of varied radii. Prefer 65-100 softness and natural or wild edges; avoid symmetrical single-pass blobs and uniform outlines.',
      transitions: 'Layer plausible transitions such as deep water to shallows to beach or rock to inland terrain, and inspect the rendered result for hard seams.',
      boundaries: 'Use cliff, hedge, wall, and palisade lines selectively where those features physically exist; do not automatically trace an entire natural landmass.',
      settlements: 'Cluster objects around access routes and shared spaces, with subtle variation in rotation and scale instead of even spacing.',
    },
    mutation_contract: 'Use a fresh UUID operation_id and the current expected_revision. Exact retries are idempotent; reusing an operation_id with different input is rejected.', deletion_contract: 'delete_map_elements requires a user-approved preview token; whole-map deletion remains a human library action',
    bulk_limits: { paint_regions: 12, paint_cells: 2000, paths: 20, path_points: 2500, elements: 50, updates: 50 }, project_tools: PROJECT_TOOL_NAMES, webmcp: true,
  })),
  tool('list_maps', 'List maps', 'List locally stored maps in compact pages.', { ...base, properties: { include_archived: { type: 'boolean' }, cursor: { type: 'integer', minimum: 0 }, limit: { type: 'integer', minimum: 1, maximum: 20 } } }, async (input) => { const available = store.projects.filter((item) => !item.deletedAt && (input.include_archived || !item.archivedAt)), cursor = Math.min(input.cursor || 0, available.length), limit = input.limit || 10, items = available.slice(cursor, cursor + limit); return result('ok', 'list_maps', `Read ${items.length} of ${available.length} local maps.`, { maps: items.map((item) => ({ id: item.id, title: item.title.slice(0, 100), type: item.mapType, revision: item.revision, archived: Boolean(item.archivedAt) })), next_cursor: cursor + limit < available.length ? cursor + limit : null, total: available.length }) }),
  tool('manage_maps', 'Manage maps', 'Create, rename, duplicate, archive, or restore a local map. Use expected_revision 0 only for create; deletion remains a human library action.', mapManagementMutation({ action: { enum: ['create', 'rename', 'duplicate', 'archive', 'restore'] }, project_id: uuidSchema, title: text(200), description: text(2000), map_type: { enum: ['dungeon', 'village', 'interior', 'wilderness', 'world'] } }, ['action']), async (input) => {
    let project
    if (input.action === 'create') { if (input.expected_revision !== 0) throw codedError('Use expected_revision 0 when creating a map.'); project = await store.createNewProject({ title: input.title, description: input.description, mapType: input.map_type }) }
    else { if (!input.project_id) throw codedError(`project_id is required for ${input.action}.`); if (input.action === 'rename' && !input.title?.trim()) throw codedError('A non-empty title is required for rename.'); const target = store.projects.find((item) => item.id === input.project_id && !item.deletedAt); if (!target) throw codedError('Map not found.', 'not_found'); if (target.revision !== input.expected_revision) throw codedError(`Expected revision ${input.expected_revision}; current revision is ${target.revision}.`, 'version_conflict'); if (input.action === 'duplicate') project = await store.duplicateProject(input.project_id); else { await store.patchProject(input.project_id, input.action === 'rename' ? { title: input.title.trim() } : input.action === 'archive' ? { archivedAt: nowIso() } : { archivedAt: null }); project = store.projects.find((item) => item.id === input.project_id) } }
    return result('ok', 'manage_maps', `${input.action} completed.`, { project_id: project?.id, revision: project?.revision })
  }, { mutation: true }),
  tool('open_map', 'Open map', 'Open a local map and reveal its stable mapmaking tools.', { ...base, properties: { project_id: uuidSchema }, required: ['project_id'] }, async (input) => { if (!store.projects.some((project) => project.id === input.project_id && !project.deletedAt)) throw codedError('Map not found.', 'not_found'); window.setTimeout(() => window.location.assign(`/maps/${input.project_id}`), 75); return result('ok', 'open_map', 'Opening the map.', { project_id: input.project_id, available_tools: PROJECT_TOOL_NAMES }) }),
] }

const active = (items = []) => items.filter((item) => !item.deletedAt)
const inRegion = (item, x, y, width, height) => item.x >= x && item.y >= y && item.x < x + width && item.y < y + height
const paginate = (items, cursor = 0, limit = 10) => ({ items: items.slice(cursor, cursor + limit), next_cursor: cursor + limit < items.length ? cursor + limit : null, total: items.length })
const maybePoints = (item, include) => include ? item.points.map(({ x, y }) => ({ x, y })) : undefined
function contextData(store, input) {
  const x = input.x ?? store.contentBounds.minX, y = input.y ?? store.contentBounds.minY, width = input.width || Math.min(20, Math.max(1, store.contentBounds.width || 12)), height = input.height || Math.min(20, Math.max(1, store.contentBounds.height || 12))
  const hasRegion = ['x', 'y', 'width', 'height'].some((key) => input[key] !== undefined)
  const detail = input.detail === 'summary' ? 'overview' : (input.detail || 'overview'), cursor = input.cursor || 0, limit = input.limit || 10, structures = active(store.bundle.structures)
  const data = { project: { id: store.bundle.project.id, title: store.bundle.project.title, description: store.bundle.project.description, type: store.bundle.project.mapType, canvas: 'endless' }, revision: store.bundle.project.revision, content_bounds: store.contentBounds }
  if (detail === 'overview') { data.counts = { terrain_cells: store.terrain.length, terrain_strokes: store.terrainStrokes.length, shapes: structures.filter((item) => item.kind === 'room').length, lines: structures.filter((item) => item.kind === 'wall-path').length, objects: active(store.bundle.objects).length, labels: active(store.bundle.labels).length }; data.layers = store.bundle.layers.map(({ id, kind, name, visible, locked, order }) => ({ id, kind, name, visible, locked, order })); data.history = { undo_available: Boolean(store.undoStack?.length), redo_available: Boolean(store.redoStack?.length) }; data.coordinate_note = 'Coordinates are signed world-space grid units. Object and label x/y are anchors; shape x/y are the top-left of its bounding box.' }
  if (detail === 'terrain') { const area = width * height; let scan = Math.min(cursor, area); const cells = []; while (scan < area && cells.length < limit) { const col = x + (scan % width), row = y + Math.floor(scan / width), value = terrainAtPoint(store.bundle, col, row) ?? terrainAt(store.bundle, col, row); if (value) cells.push({ x: col, y: row, terrain: value }); scan += 1 } const strokes = store.terrainStrokes.filter((stroke) => stroke.bounds.maxX >= x && stroke.bounds.minX <= x + width && stroke.bounds.maxY >= y && stroke.bounds.minY <= y + height).slice(0, limit).map((stroke) => ({ id: stroke.id, terrain: stroke.terrain, mode: stroke.mode, radius: stroke.radius, edge: stroke.edge, softness: Math.round((stroke.softness ?? .75) * 100), bounds: { ...stroke.bounds }, point_count: stroke.points.length, points: maybePoints(stroke, input.include_geometry) })); data.region = { x, y, width, height, cells, strokes, next_cursor: scan < area ? scan : null } }
  if (detail === 'objects') { const records = active(store.bundle.objects), p = paginate(hasRegion ? records.filter((item) => inRegion(item, x, y, width, height)) : records, cursor, limit); data.objects = p.items.map(({ id, assetId, x: px, y: py, rotation, scale, zIndex }) => ({ id, asset_id: assetId, x: px, y: py, rotation, scale, z_index: zIndex || 0 })); data.next_cursor = p.next_cursor; data.total = p.total }
  if (detail === 'shapes') { const records = structures.filter((item) => item.kind === 'room'), p = paginate(hasRegion ? records.filter((item) => inRegion(item, x, y, width, height)) : records, cursor, limit); data.shapes = p.items.map((item) => ({ id: item.id, shape: item.shape, x: item.x, y: item.y, width: item.width, height: item.height, rotation: item.rotation || 0, sides: item.sides, inner_ratio: item.innerRatio, floor_terrain: item.floorTerrain, line_style: item.lineStyle, wall_terrain: item.wallTerrain, wall_width: item.wallWidth, z_index: item.zIndex || 0, points: maybePoints(item, input.include_geometry) })); data.next_cursor = p.next_cursor; data.total = p.total }
  if (detail === 'lines') { const records = structures.filter((item) => item.kind === 'wall-path'), p = paginate(hasRegion ? records.filter((item) => item.points?.some((point) => inRegion(point, x, y, width, height))) : records, cursor, limit); data.lines = p.items.map((item) => ({ id: item.id, point_count: item.points.length, points: maybePoints(item, input.include_geometry), line_style: item.lineStyle, wall_terrain: item.wallTerrain, wall_width: item.wallWidth, closed: Boolean(item.closed), z_index: item.zIndex || 0 })); data.next_cursor = p.next_cursor; data.total = p.total }
  if (detail === 'labels') { const records = active(store.bundle.labels), p = paginate(hasRegion ? records.filter((item) => inRegion(item, x, y, width, height)) : records, cursor, limit); data.labels = p.items.map((item) => ({ id: item.id, text: item.text, x: item.x, y: item.y, box_width: item.boxWidth, box_height: item.boxHeight, rotation: item.rotation || 0, font_size: item.fontSize, size: item.size, font: item.font, color: item.color, bold: Boolean(item.bold) })); data.next_cursor = p.next_cursor; data.total = p.total }
  if (detail === 'layers') data.layers = store.bundle.layers.map(({ id, kind, name, visible, locked, order }) => ({ id, kind, name, visible, locked, order }))
  return data
}

const objectUpdateSchema = { ...base, properties: { kind: { const: 'object' }, id: uuidSchema, asset_id: { enum: objectIds }, x: coordinate, y: coordinate, rotation: { type: 'number', minimum: -36000, maximum: 36000 }, scale: { type: 'number', minimum: .5, maximum: 3 }, z_index: { type: 'integer', minimum: 0, maximum: 1000000 } }, required: ['kind', 'id'] }
const shapeUpdateSchema = { ...base, properties: { kind: { const: 'shape' }, id: uuidSchema, shape: { enum: shapeTypes }, x: coordinate, y: coordinate, width: { type: 'number', minimum: 1, maximum: 80 }, height: { type: 'number', minimum: 1, maximum: 80 }, rotation: { type: 'number', minimum: -36000, maximum: 36000 }, sides: { type: 'integer', minimum: 3, maximum: 12 }, inner_ratio: { type: 'number', minimum: .15, maximum: .8 }, floor_terrain: { enum: terrainIds }, line_style: { enum: lineStyleIds }, wall_terrain: { enum: terrainIds }, wall_width: { type: 'number', minimum: .12, maximum: 1.5 }, z_index: { type: 'integer', minimum: 0, maximum: 1000000 } }, required: ['kind', 'id'] }
const lineUpdateSchema = { ...base, properties: { kind: { const: 'line' }, id: uuidSchema, points: linePointsSchema(500), line_style: { enum: lineStyleIds }, wall_terrain: { enum: terrainIds }, wall_width: { type: 'number', minimum: .12, maximum: 1.5 }, closed: { type: 'boolean' }, z_index: { type: 'integer', minimum: 0, maximum: 1000000 } }, required: ['kind', 'id'] }
const labelUpdateSchema = { ...base, properties: { kind: { const: 'label' }, id: uuidSchema, text: labelTextSchema, x: coordinate, y: coordinate, box_width: { type: ['number', 'null'], minimum: 1, maximum: 80 }, box_height: { type: ['number', 'null'], minimum: 1, maximum: 80 }, rotation: { type: 'number', minimum: -36000, maximum: 36000 }, font_size: { type: ['number', 'null'], minimum: .35, maximum: 8 }, size: { enum: labelSizeIds }, font: { enum: labelFontIds }, color: labelColorSchema, bold: { type: 'boolean' } }, required: ['kind', 'id'] }
const lineStyle = (id) => LINE_STYLES.find((item) => item.id === id) || LINE_STYLES[0]
function updatePlan(store, updates) { const seen = new Set(); return updates.map((update) => { if (seen.has(update.id)) throw codedError(`Element ${update.id} appears more than once.`); seen.add(update.id); const keys = Object.keys(update).filter((key) => !['kind', 'id'].includes(key)); if (!keys.length) throw codedError(`Element ${update.id} has no changes.`); const listName = update.kind === 'object' ? 'objects' : update.kind === 'label' ? 'labels' : 'structures', targetKind = update.kind === 'shape' ? 'room' : update.kind === 'line' ? 'wall-path' : null, target = store.bundle[listName].find((item) => item.id === update.id && !item.deletedAt && (!targetKind || item.kind === targetKind)); if (!target) throw codedError(`${update.kind} ${update.id} was not found.`, 'not_found'); const patch = {}, map = { asset_id: 'assetId', inner_ratio: 'innerRatio', floor_terrain: 'floorTerrain', line_style: 'lineStyle', wall_terrain: 'wallTerrain', wall_width: 'wallWidth', z_index: 'zIndex', box_width: 'boxWidth', box_height: 'boxHeight', font_size: 'fontSize' }; for (const key of keys) patch[map[key] || key] = update[key]; if (update.line_style) { const style = lineStyle(update.line_style); if (update.wall_terrain === undefined) patch.wallTerrain = style.terrain; if (update.wall_width === undefined) patch.wallWidth = style.width } if (update.kind === 'line') { const closed = update.closed ?? target.closed; let points = update.points || target.points; const sameEnds = stable(points[0]) === stable(points.at(-1)); if (closed && !sameEnds) points = [...points, points[0]]; else if (!closed && sameEnds) points = points.slice(0, -1); if (update.points || update.closed !== undefined) patch.points = points } if (update.kind === 'shape') { const points = roomShapePoints({ ...target, ...patch }); if (points.some(({ x, y }) => Math.abs(x) > WORLD_COORDINATE_LIMIT || Math.abs(y) > WORLD_COORDINATE_LIMIT)) throw codedError(`Shape ${update.id} would extend beyond the coordinate limit.`) } return { id: update.id, kind: update.kind, listName, patch } }) }

function projectTools(store) {
  const revision = () => store.bundle.project.revision
  return [
    tool('get_map_context', 'Read map context', 'Read the map overview or a bounded, paged content type. Use include_geometry for exact shape, line, or terrain-stroke points before modifying geometry.', { ...base, properties: { x: coordinate, y: coordinate, width: { type: 'integer', minimum: 1, maximum: 20 }, height: { type: 'integer', minimum: 1, maximum: 20 }, detail: { enum: ['overview', 'summary', 'terrain', 'objects', 'shapes', 'lines', 'labels', 'layers'] }, cursor: { type: 'integer', minimum: 0, maximum: 50000 }, limit: { type: 'integer', minimum: 1, maximum: 20 }, include_geometry: { type: 'boolean' } } }, async (input) => result('ok', 'get_map_context', 'Read the requested map context.', contextData(store, input))),
    tool('get_map_asset_catalog', 'Read map style catalog', 'List terrain, objects, line styles, label styles, or supported shape types. Use kind for full details.', { ...base, properties: { kind: { enum: ['terrain', 'objects', 'line_styles', 'label_styles', 'shapes'] } } }, async (input) => { let data; if (input.kind === 'terrain') data = { terrain: TERRAIN.map(({ id, label }) => ({ id, label })) }; else if (input.kind === 'objects') data = { objects: OBJECTS.map(({ id, label, width, height }) => ({ id, label, width, height })) }; else if (input.kind === 'line_styles') data = { line_styles: LINE_STYLES.map(({ id, label, description, terrain, width }) => ({ id, label, description, default_terrain: terrain, default_width: width })) }; else if (input.kind === 'label_styles') data = { sizes: LABEL_SIZES.map(({ id, label }) => ({ id, label })), fonts: LABEL_FONTS.map(({ id, label }) => ({ id, label })), colors: LABEL_COLORS }; else if (input.kind === 'shapes') data = { shapes: shapeTypes, polygon_sides: [3, 12], star_inner_ratio: [.15, .8] }; else data = { terrain_ids: terrainIds, object_ids: objectIds, line_style_ids: lineStyleIds, label_size_ids: labelSizeIds, label_font_ids: labelFontIds, label_color_ids: labelColorIds, shape_types: shapeTypes }; return result('ok', 'get_map_asset_catalog', 'Read the map style catalog.', data) }),
    tool('paint_map_regions', 'Paint map regions', 'Paint precise cell-defined or intentionally blocky terrain regions. Prefer paint_map_strokes for coastlines, forests, fields, and other organic geography.', mutation({ regions: { type: 'array', minItems: 1, maxItems: 12, items: { ...base, properties: { terrain: { enum: terrainIds }, edge: terrainEdgeSchema, cells: cellsSchema }, required: ['terrain', 'cells'] } } }, ['regions']), async (input) => { ensureRevision(store, input); const count = input.regions.reduce((sum, region) => sum + region.cells.length, 0); if (count > 2000) throw codedError('A single paint operation may contain at most 2,000 region cells.'); await store.paintRegions(input.regions); return result('ok', 'paint_map_regions', `Painted ${count} cells across ${input.regions.length} terrain regions.`, { revision: revision(), regions: input.regions.length, cells: count, content_bounds: store.contentBounds }) }, { mutation: true }),
    tool('paint_map_strokes', 'Paint map strokes', 'Paint organic terrain with continuous coordinates, varied radii, edge character, and softness. For natural forms, overlap offset strokes rather than outlining one symmetrical shape.', mutation({ strokes: { type: 'array', minItems: 1, maxItems: 20, items: { ...base, properties: { terrain: { enum: terrainIds }, edge: terrainEdgeSchema, softness: terrainSoftnessSchema, radius: { type: 'number', minimum: .125, maximum: 12, description: 'Brush radius in map cells. Vary radii across overlapping strokes to avoid uniform silhouettes.' }, points: pointsSchema(500) }, required: ['terrain', 'radius', 'points'] } } }, ['strokes']), async (input, options) => { ensureRevision(store, input); const count = input.strokes.reduce((sum, stroke) => sum + stroke.points.length, 0); if (count > 2500) throw codedError('A single paint operation may contain at most 2,500 path points.'); if (options.signal?.aborted) throw codedError('The action was cancelled.', 'cancelled'); const created = await store.paintStrokes(input.strokes.map((stroke) => ({ ...stroke, softness: (stroke.softness ?? 100) / 100, mode: 'paint', discrete: false }))); return result('ok', 'paint_map_strokes', `Painted ${created.length} continuous terrain strokes.`, { revision: revision(), created: created.map(({ id }) => id), points: count }) }, { mutation: true }),
    tool('erase_map_terrain', 'Erase map terrain', 'Erase only terrain along continuous paths; semantic objects, shapes, lines, and labels are preserved. Use softer overlapping passes for natural erosion and hard passes for deliberate cutouts.', mutation({ strokes: { type: 'array', minItems: 1, maxItems: 20, items: { ...base, properties: { edge: terrainEdgeSchema, softness: eraseSoftnessSchema, radius: { type: 'number', minimum: .125, maximum: 12 }, points: pointsSchema(500) }, required: ['radius', 'points'] } } }, ['strokes']), async (input) => { ensureRevision(store, input); const count = input.strokes.reduce((sum, stroke) => sum + stroke.points.length, 0); if (count > 2500) throw codedError('A single erase operation may contain at most 2,500 path points.'); const created = await store.paintStrokes(input.strokes.map((stroke) => ({ ...stroke, terrain: null, softness: (stroke.softness ?? 0) / 100, mode: 'erase', discrete: false }))); return result('ok', 'erase_map_terrain', `Erased terrain with ${created.length} strokes.`, { revision: revision(), created: created.map(({ id }) => id), points: count }) }, { mutation: true }),
    tool('create_map_shapes', 'Create map shapes', 'Create editable rectangle, ellipse, polygon, or star shapes with floor terrain and styled boundaries.', mutation({ shapes: { type: 'array', minItems: 1, maxItems: 20, items: { ...base, properties: { x: coordinate, y: coordinate, width: { type: 'number', minimum: 1, maximum: 80 }, height: { type: 'number', minimum: 1, maximum: 80 }, shape: { enum: shapeTypes }, rotation: { type: 'number', minimum: -36000, maximum: 36000 }, sides: { type: 'integer', minimum: 3, maximum: 12 }, inner_ratio: { type: 'number', minimum: .15, maximum: .8 }, floor_terrain: { enum: terrainIds }, line_style: { enum: lineStyleIds }, wall_terrain: { enum: terrainIds }, wall_width: { type: 'number', minimum: .12, maximum: 1.5 }, z_index: { type: 'integer', minimum: 0, maximum: 1000000 } }, required: ['x', 'y', 'width', 'height'] } } }, ['shapes']), async (input) => { ensureRevision(store, input); const created = await store.createRooms(input.shapes.map((shape) => { const style = lineStyle(shape.line_style || store.selectedLineStyle); return { ...shape, terrain: shape.floor_terrain || 'stone', innerRatio: shape.inner_ratio, lineStyle: style.id, wallTerrain: shape.wall_terrain || style.terrain, wallWidth: shape.wall_width ?? style.width, zIndex: shape.z_index } })); return result('ok', 'create_map_shapes', `Created ${created.length} editable shapes.`, { revision: revision(), shapes: created.map(({ id, shape, x, y }) => ({ id, shape, x, y })) }) }, { mutation: true }),
    tool('draw_map_lines', 'Draw map lines', 'Draw styled walls, palisades, cliffs, or hedges. For natural maps, place cliffs and hedges only where the feature exists instead of tracing every terrain boundary.', mutation({ lines: { type: 'array', minItems: 1, maxItems: 20, items: { ...base, properties: { points: linePointsSchema(500), line_style: { enum: lineStyleIds }, wall_terrain: { enum: terrainIds }, wall_width: { type: 'number', minimum: .12, maximum: 1.5 }, closed: { type: 'boolean' }, z_index: { type: 'integer', minimum: 0, maximum: 1000000 } }, required: ['points'] } } }, ['lines']), async (input, options) => { ensureRevision(store, input); const count = input.lines.reduce((sum, line) => sum + line.points.length, 0); if (count > 2500) throw codedError('A single line operation may contain at most 2,500 path points.'); const paths = input.lines.map((line) => { if (options.signal?.aborted) throw codedError('The action was cancelled.', 'cancelled'); const style = lineStyle(line.line_style || store.selectedLineStyle), points = line.closed && stable(line.points[0]) !== stable(line.points.at(-1)) ? [...line.points, line.points[0]] : line.points; return { points, lineStyle: style.id, wallTerrain: line.wall_terrain || style.terrain, wallWidth: line.wall_width ?? style.width, closed: Boolean(line.closed), zIndex: line.z_index } }); const created = await store.drawWallPaths(paths); return result('ok', 'draw_map_lines', `Drew ${created.length} styled lines.`, { revision: revision(), lines: created.map(({ id, points, lineStyle: style }) => ({ id, point_count: points.length, line_style: style })) }) }, { mutation: true }),
    tool('place_map_objects', 'Place map objects', 'Place semantic landmarks, props, trees, buildings, or furniture. Cluster related objects around paths and shared spaces, and use subtle rotation and scale variation to avoid mechanical spacing.', mutation({ objects: { type: 'array', minItems: 1, maxItems: 50, items: { ...base, properties: { asset_id: { enum: objectIds }, x: coordinate, y: coordinate, rotation: { type: 'number', minimum: -36000, maximum: 36000 }, scale: { type: 'number', minimum: .5, maximum: 3 }, z_index: { type: 'integer', minimum: 0, maximum: 1000000 } }, required: ['asset_id', 'x', 'y'] } } }, ['objects']), async (input) => { ensureRevision(store, input); const created = await store.placeObjects(input.objects.map((item) => ({ ...item, assetId: item.asset_id, zIndex: item.z_index }))); return result('ok', 'place_map_objects', `Placed ${created.length} map objects.`, { revision: revision(), objects: created.map(({ id, assetId, x, y }) => ({ id, asset_id: assetId, x, y })) }) }, { mutation: true }),
    tool('add_map_labels', 'Add map labels', 'Add editable text boxes with size, font, custom color, weight, rotation, and bounds.', mutation({ labels: { type: 'array', minItems: 1, maxItems: 30, items: { ...base, properties: { text: labelTextSchema, x: coordinate, y: coordinate, box_width: { type: 'number', minimum: 1, maximum: 80 }, box_height: { type: 'number', minimum: 1, maximum: 80 }, rotation: { type: 'number', minimum: -36000, maximum: 36000 }, font_size: { type: 'number', minimum: .35, maximum: 8 }, size: { enum: labelSizeIds }, font: { enum: labelFontIds }, color: labelColorSchema, bold: { type: 'boolean' } }, required: ['text', 'x', 'y'] } } }, ['labels']), async (input) => { ensureRevision(store, input); const created = await store.addLabels(input.labels.map((label) => ({ ...label, boxWidth: label.box_width, boxHeight: label.box_height, fontSize: label.font_size }))); return result('ok', 'add_map_labels', `Added ${created.length} styled text boxes.`, { revision: revision(), labels: created.map(({ id, text: value, x, y }) => ({ id, text: value, x, y })) }) }, { mutation: true }),
    tool('update_map_elements', 'Update map elements', 'Update existing objects, shapes, lines, or labels by stable ID. Omitted properties remain unchanged.', mutation({ updates: { type: 'array', minItems: 1, maxItems: 50, items: { oneOf: [objectUpdateSchema, shapeUpdateSchema, lineUpdateSchema, labelUpdateSchema] } } }, ['updates']), async (input) => { ensureRevision(store, input); const plan = updatePlan(store, input.updates), stores = [...new Set(plan.map(({ listName }) => listName))]; await store.commit((draft) => { for (const change of plan) { const target = draft[change.listName].find((item) => item.id === change.id && !item.deletedAt); Object.assign(target, change.patch, { updatedAt: nowIso() }); if (change.kind === 'shape') target.points = roomShapePoints(target) } }, { stores }); return result('ok', 'update_map_elements', `Updated ${plan.length} map elements.`, { revision: revision(), updated: plan.map(({ id, kind }) => ({ id, kind })) }) }, { mutation: true }),
    tool('set_map_layer_visibility', 'Set map layer visibility', 'Show or hide terrain, structure, object, or label layers without deleting content.', mutation({ layers: { type: 'array', minItems: 1, maxItems: 4, items: { ...base, properties: { kind: { enum: layerKinds }, visible: { type: 'boolean' } }, required: ['kind', 'visible'] } } }, ['layers']), async (input) => { ensureRevision(store, input); if (new Set(input.layers.map(({ kind }) => kind)).size !== input.layers.length) throw codedError('Each layer kind may appear only once.'); await store.commit((draft) => { for (const requested of input.layers) { const layer = draft.layers.find(({ kind }) => kind === requested.kind); if (!layer) throw codedError(`Layer ${requested.kind} was not found.`, 'not_found'); layer.visible = requested.visible } }, { stores: ['layers'] }); return result('ok', 'set_map_layer_visibility', `Updated ${input.layers.length} layer visibility settings.`, { revision: revision(), layers: input.layers }) }, { mutation: true }),
    tool('change_map_history', 'Undo or redo map change', 'Undo or redo one recoverable local map change.', mutation({ action: { enum: ['undo', 'redo'] } }, ['action']), async (input) => { ensureRevision(store, input); const stack = input.action === 'undo' ? store.undoStack : store.redoStack; if (!stack?.length) throw codedError(`There is nothing to ${input.action}.`, `nothing_to_${input.action}`); await store[input.action](); return result('ok', 'change_map_history', `${input.action === 'undo' ? 'Undid' : 'Redid'} one map change.`, { revision: revision(), undo_available: Boolean(store.undoStack.length), redo_available: Boolean(store.redoStack.length) }) }, { mutation: true }),
    tool('delete_map_elements', 'Remove map elements', 'Recoverably remove objects, labels, shapes, or lines by authoritative ID after human approval.', mutation({ ids: { type: 'array', minItems: 1, maxItems: 100, uniqueItems: true, items: uuidSchema } }, ['ids', 'risk']), async (input) => { ensureRevision(store, input); const lists = ['objects', 'labels', 'structures'], found = new Set(lists.flatMap((list) => active(store.bundle[list]).filter((item) => input.ids.includes(item.id)).map(({ id }) => id))), missing = input.ids.filter((id) => !found.has(id)); if (missing.length) throw codedError(`Map elements not found: ${missing.join(', ')}.`, 'not_found'); await store.commit((draft) => { for (const list of lists) for (const item of draft[list]) if (found.has(item.id)) item.deletedAt = nowIso() }, { stores: lists }); store.selection = null; return result('ok', 'delete_map_elements', `Removed ${found.size} map elements.`, { revision: revision(), removed: [...found] }) }, { mutation: true, risky: true }),
    tool('export_map', 'Export map', 'Export current content bounds as PNG, portable archive, or map notes.', mutation({ format: { enum: ['png', 'archive', 'notes'] } }, ['format']), async (input) => { ensureRevision(store, input); if (input.format === 'png') await exportMapPng(store.bundle); else if (input.format === 'archive') await exportMapArchive(store.bundle); else exportMapNotes(store.bundle); return result('ok', 'export_map', `Prepared the ${input.format} export.`, { revision: revision(), format: input.format, bounds: store.contentBounds }) }, { mutation: true }),
  ]
}

export function useWebMcp(store, router) {
  let projectDisposer
  const libraryDisposer = registerScope('library', libraryTools(store))
  const stopProject = watch(() => [router.currentRoute.value.params.id, store.bundle?.project.id, store.locale], ([id, bundleId]) => { projectDisposer?.(); projectDisposer = null; if (id && bundleId === id) projectDisposer = registerScope('project', projectTools(store)) }, { immediate: true, flush: 'post' })
  return () => { stopProject(); projectDisposer?.(); libraryDisposer() }
}

export const webMcpTestApi = { supported, registerScope, disposeScope, runTool, projectTools, libraryTools, previews, operations, stable, OUTPUT_LIMIT, PROJECT_TOOL_NAMES }
