import Ajv from 'ajv'
import { watch } from 'vue'
import { LIMITS, OBJECTS, TERRAIN, nowIso, uuid } from '../constants.js'
import { exportMapArchive, exportMapNotes, exportMapPng } from './portability.js'
import { showWebMcpActivity } from './webMcpState.js'

const ajv=new Ajv({allErrors:true,strict:false}),scopes=new Map(),previews=new Map(),operations=new Map();ajv.addFormat('uuid',/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)
const base={type:'object',additionalProperties:false},uuidSchema={type:'string',format:'uuid'},text=(max=2000)=>({type:'string',maxLength:max}),operation={operation_id:uuidSchema,expected_revision:{type:'integer',minimum:1}},riskSchema={type:'object',additionalProperties:false,properties:{preview:{type:'boolean'},preview_token:{type:'string',maxLength:100}},required:['preview']}
const mutation=(properties,required=[])=>({...base,properties:{...operation,...properties,risk:riskSchema},required:['operation_id','expected_revision',...required]})
const result=(status,action,message,data={},error_code=null)=>({status,action,message,effects:[],verification:{visible:true,save_state:status==='ok'?'saved':'unchanged',route:location.pathname},data,warnings:[],next_actions:[],error_code})
const stable=(value)=>JSON.stringify(value,Object.keys(value||{}).sort())
const supported=()=>import.meta.env.VITE_WEBMCP_ENABLED!=='false'&&typeof document!=='undefined'&&window.top===window&&(globalThis.isSecureContext||['localhost','127.0.0.1'].includes(location.hostname))&&typeof document.modelContext?.registerTool==='function'
const compact=(value)=>JSON.stringify(value).length<=1500?value:{...value,data:{truncated:true,summary:'Result exceeds the page output budget. Request a smaller region or page.'}}
const tool=(name,title,description,inputSchema,execute,{mutation=false,risky=false}={})=>({name,title,description,inputSchema,execute,mutation,risky,annotations:{readOnlyHint:!mutation,destructiveHint:risky,untrustedContentHint:!mutation}})
function ensureRevision(store,input){if(input.expected_revision!==store.bundle.project.revision)throw Object.assign(new Error(`Expected revision ${input.expected_revision}; current revision is ${store.bundle.project.revision}.`),{code:'version_conflict'})}
function opKey(name,input){return `${name}:${input.operation_id}:${stable({...input,risk:undefined})}`}
async function runTool(def,input,options={}){showWebMcpActivity('working','Mapworks is drawing',def.title,0);try{if(options.signal?.aborted)throw Object.assign(new Error('The action was cancelled.'),{code:'cancelled'});const validate=ajv.compile(def.inputSchema);if(!validate(input))throw Object.assign(new Error(validate.errors.map((error)=>`${error.instancePath||'input'} ${error.message}`).join('; ')),{code:'invalid_input'});const key=input.operation_id&&opKey(def.name,input);if(key&&operations.has(key))return operations.get(key);if(def.risky){const canonical=opKey(def.name,{...input,risk:undefined}),risk=input.risk||{};if(risk.preview){const approved=window.confirm(`Allow Mapworks to ${def.title.toLowerCase()}?\n\nThe current map revision will be checked again before anything changes.`);if(!approved)return result('cancelled',def.name,'You cancelled the proposed map change.');const token=uuid();previews.set(token,{canonical,revision:input.expected_revision,expires:Date.now()+600000,used:false});return result('preview',def.name,'The map change is approved and ready to commit.',{preview_token:token,expires_in_seconds:600});}const approval=previews.get(risk.preview_token);if(!approval||approval.expires<Date.now())throw Object.assign(new Error('Preview approval is missing or expired.'),{code:'preview_expired'});if(approval.used)throw Object.assign(new Error('Preview approval was already used.'),{code:'preview_consumed'});if(approval.canonical!==canonical||approval.revision!==input.expected_revision)throw Object.assign(new Error('The map request changed after approval.'),{code:'preview_required'});approval.used=true}const out=compact(await def.execute(input,options));if(key)operations.set(key,out);showWebMcpActivity(out.status,'Map updated',out.message);return out}catch(error){const out=result(error.code==='cancelled'?'cancelled':'error',def.name,error.message,{},error.code||'save_failed');showWebMcpActivity(out.status,'Mapworks paused',out.message,6000);return out}}
function registerScope(name,tools){disposeScope(name);const controller=new AbortController();scopes.set(name,{controller,tools});if(supported())queueMicrotask(()=>tools.forEach((entry)=>Promise.resolve(document.modelContext.registerTool({...entry,execute:(input,options={})=>runTool(entry,input,{...options,signal:options.signal||controller.signal})},{signal:controller.signal})).catch((error)=>{if(!controller.signal.aborted)console.warn('WebMCP registration failed',error)})));return()=>disposeScope(name)}
function disposeScope(name){scopes.get(name)?.controller.abort();scopes.delete(name);previews.clear()}
const cellsSchema={type:'array',minItems:1,maxItems:500,items:{...base,properties:{x:{type:'integer',minimum:0,maximum:95},y:{type:'integer',minimum:0,maximum:95}},required:['x','y']}}
function libraryTools(store,router){return[
  tool('get_mapworks_capabilities','Describe Mapworks','Learn what this local fantasy map builder and its page-aware tools can do.',base,async()=>result('ok','get_mapworks_capabilities','Mapworks is ready for local mapmaking.',{storage:'local IndexedDB',map_types:['dungeon','village','interior','wilderness','world'],limits:LIMITS,terrain:TERRAIN.map((item)=>item.id),objects:OBJECTS.map((item)=>item.id),webmcp:true})),
  tool('list_maps','List maps','List locally stored maps.',{...base,properties:{include_archived:{type:'boolean'}}},async(input)=>result('ok','list_maps',`Found ${store.projects.length} local maps.`,{maps:store.projects.filter((item)=>!item.deletedAt&&(input.include_archived||!item.archivedAt)).slice(0,30).map((item)=>({id:item.id,title:item.title,type:item.mapType,size:[item.width,item.height],revision:item.revision}))})),
  tool('manage_maps','Manage maps','Create, rename, duplicate, archive, restore, or recoverably delete a local map.',mutation({action:{enum:['create','rename','duplicate','archive','restore','delete']},project_id:uuidSchema,title:text(200),description:text(2000),map_type:{enum:['dungeon','village','interior','wilderness','world']},width:{type:'integer',minimum:8,maximum:96},height:{type:'integer',minimum:8,maximum:96}},['action']),async(input)=>{let project;if(input.action==='create')project=await store.createNewProject({title:input.title,description:input.description,mapType:input.map_type,width:input.width,height:input.height});else if(input.action==='duplicate')project=await store.duplicateProject(input.project_id);else{await store.patchProject(input.project_id,input.action==='rename'?{title:input.title}:input.action==='archive'?{archivedAt:nowIso()}:input.action==='restore'?{archivedAt:null}:{deletedAt:nowIso()});project=store.projects.find((item)=>item.id===input.project_id)}return result('ok','manage_maps',`${input.action} completed.`,{project_id:project?.id})},{mutation:true}),
  tool('open_map','Open map','Open a local map and reveal its mapmaking tools.',{...base,properties:{project_id:uuidSchema},required:['project_id']},async(input)=>{await router.push(`/maps/${input.project_id}`);return result('ok','open_map','Opened the map.',{project_id:input.project_id,available_tools:projectTools(store).map((item)=>item.name)})}),
]}
function projectTools(store){const revision=()=>store.bundle.project.revision;return[
  tool('get_map_context','Read map context','Read map metadata, layers, a bounded tile region, objects, labels, selection, and revision.',{...base,properties:{x:{type:'integer',minimum:0},y:{type:'integer',minimum:0},width:{type:'integer',minimum:1,maximum:20},height:{type:'integer',minimum:1,maximum:20}}},async(input)=>{const x=input.x||0,y=input.y||0,width=Math.min(input.width||12,store.bundle.project.width-x),height=Math.min(input.height||12,store.bundle.project.height-y),tiles=[];for(let row=y;row<y+height;row++)tiles.push(store.terrain.slice(row*store.bundle.project.width+x,row*store.bundle.project.width+x+width));return result('ok','get_map_context','Read the visible map context.',{project:{id:store.bundle.project.id,title:store.bundle.project.title,type:store.bundle.project.mapType,size:[store.bundle.project.width,store.bundle.project.height]},revision:revision(),region:{x,y,width,height,tiles},layers:store.bundle.layers.map((layer)=>({id:layer.id,kind:layer.kind,visible:layer.visible})),objects:store.visibleObjects.filter((item)=>item.x>=x&&item.y>=y&&item.x<x+width&&item.y<y+height).slice(0,30).map(({id,assetId,x,y,rotation,hidden})=>({id,assetId,x,y,rotation,hidden})),labels:store.visibleLabels.slice(0,20).map(({id,text,x,y,hidden})=>({id,text:text.slice(0,120),x,y,hidden}))})}),
  tool('get_map_asset_catalog','Read map asset catalog','List terrain textures and placeable objects available on this page.',base,async()=>result('ok','get_map_asset_catalog','Read the hand-painted map asset catalog.',{terrain:TERRAIN,objects:OBJECTS})),
  tool('paint_map_terrain','Paint map terrain','Paint up to 500 authoritative grid cells in one durable operation.',mutation({terrain:{enum:TERRAIN.map((item)=>item.id)},cells:cellsSchema},['terrain','cells']),async(input)=>{ensureRevision(store,input);await store.paintCells(input.cells,input.terrain);return result('ok','paint_map_terrain',`Painted ${input.cells.length} ${input.terrain} tiles.`,{revision:revision()})},{mutation:true}),
  tool('create_map_rooms','Create map rooms','Create up to twenty rectangular rooms with floors and enclosing walls.',mutation({rooms:{type:'array',minItems:1,maxItems:20,items:{...base,properties:{x:{type:'integer',minimum:0},y:{type:'integer',minimum:0},width:{type:'integer',minimum:3,maximum:40},height:{type:'integer',minimum:3,maximum:40},terrain:{enum:TERRAIN.map((item)=>item.id)}},required:['x','y','width','height']}}},['rooms']),async(input)=>{ensureRevision(store,input);await store.createRooms(input.rooms);return result('ok','create_map_rooms',`Built ${input.rooms.length} rooms.`,{revision:revision()})},{mutation:true}),
  tool('draw_map_walls','Draw map walls','Draw up to 500 wall cells in one durable operation.',mutation({cells:cellsSchema},['cells']),async(input)=>{ensureRevision(store,input);await store.drawWalls(input.cells);return result('ok','draw_map_walls',`Drew ${input.cells.length} wall sections.`,{revision:revision()})},{mutation:true}),
  tool('place_map_objects','Place map objects','Place up to fifty semantic landmarks, props, trees, buildings, or furniture pieces.',mutation({objects:{type:'array',minItems:1,maxItems:50,items:{...base,properties:{assetId:{enum:OBJECTS.map((item)=>item.id)},x:{type:'integer',minimum:0},y:{type:'integer',minimum:0},rotation:{type:'integer',minimum:0,maximum:359},scale:{type:'number',minimum:.5,maximum:3},hidden:{type:'boolean'}},required:['assetId','x','y']}}},['objects']),async(input)=>{ensureRevision(store,input);const created=await store.placeObjects(input.objects);return result('ok','place_map_objects',`Placed ${created.length} map objects.`,{revision:revision(),objects:created.map(({id,assetId,x,y})=>({id,assetId,x,y}))})},{mutation:true}),
  tool('label_map_regions','Label map regions','Add up to thirty visible or game-master-only labels.',mutation({labels:{type:'array',minItems:1,maxItems:30,items:{...base,properties:{text:text(200),x:{type:'integer',minimum:0},y:{type:'integer',minimum:0},size:{enum:['small','medium','large']},hidden:{type:'boolean'}},required:['text','x','y']}}},['labels']),async(input)=>{ensureRevision(store,input);const created=await store.addLabels(input.labels);return result('ok','label_map_regions',`Added ${created.length} map labels.`,{revision:revision(),labels:created.map(({id,text,x,y})=>({id,text,x,y}))})},{mutation:true}),
  tool('delete_map_elements','Remove map elements','Recoverably remove objects or labels by authoritative ID after human approval.',mutation({ids:{type:'array',minItems:1,maxItems:100,items:uuidSchema}},['ids','risk']),async(input)=>{ensureRevision(store,input);await store.commit((draft)=>{for(const list of [draft.objects,draft.labels,draft.structures])for(const item of list)if(input.ids.includes(item.id))item.deletedAt=nowIso()});store.selection=null;return result('ok','delete_map_elements',`Removed ${input.ids.length} map elements.`,{revision:revision(),ids:input.ids})},{mutation:true,risky:true}),
  tool('export_map','Export map','Visibly prepare and download a PNG, portable archive, or map notes.',mutation({format:{enum:['png','archive','notes']}},['format']),async(input)=>{ensureRevision(store,input);if(input.format==='png'){const element=document.querySelector('.map-stage');if(!element)throw Object.assign(new Error('The map is not visible.'),{code:'unsupported'});await exportMapPng(element,store.bundle)}else if(input.format==='archive')await exportMapArchive(store.bundle);else exportMapNotes(store.bundle);return result('ok','export_map',`Prepared the ${input.format} export.`,{revision:revision(),format:input.format})},{mutation:true}),
]}
export function useWebMcp(store,router){let projectDisposer;const libraryDisposer=registerScope('library',libraryTools(store,router));const stop=watch(()=>[router.currentRoute.value.params.id,store.bundle?.project.id,store.locale],([id,bundleId])=>{projectDisposer?.();projectDisposer=null;if(id&&bundleId===id)projectDisposer=registerScope('project',projectTools(store))},{immediate:true,flush:'post'});return()=>{stop();projectDisposer?.();libraryDisposer()}}
export const webMcpTestApi={supported,registerScope,disposeScope,runTool,projectTools,libraryTools,previews,operations}
