import Ajv from 'ajv'
import { uuid } from '../constants.js'
import { showWebMcpActivity } from './webMcpState.js'

export const OUTPUT_LIMIT=12000
const OPERATION_LIMIT=200,PREVIEW_TTL=10*60*1000,ajv=new Ajv({allErrors:true,strict:false}),validators=new WeakMap(),scopes=new Map()
export const previews=new Map(),operations=new Map()
ajv.addFormat('uuid',/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)

export const result=(status,action,message,data={},error_code=null)=>({status,action,message,effects:[],verification:{visible:true,save_state:status==='ok'?'saved':'unchanged',route:globalThis.location?.pathname||'/'},data,warnings:[],next_actions:[],error_code})
function canonicalize(value){if(Array.isArray(value))return value.map(canonicalize);if(!value||typeof value!=='object')return value;return Object.fromEntries(Object.keys(value).sort().filter((key)=>value[key]!==undefined).map((key)=>[key,canonicalize(value[key])]))}
export const stable=(value)=>JSON.stringify(canonicalize(value))
export const supported=()=>import.meta.env.VITE_WEBMCP_ENABLED!=='false'&&typeof document!=='undefined'&&window.top===window&&(globalThis.isSecureContext||['localhost','127.0.0.1'].includes(location.hostname))&&typeof document.modelContext?.registerTool==='function'
const compact=(value)=>JSON.stringify(value).length<=OUTPUT_LIMIT?value:result('error',value.action||'unknown','The result exceeded the WebMCP output budget. Request a smaller page or region.',{truncated:true,output_limit:OUTPUT_LIMIT},'result_too_large')
export const tool=(name,title,description,inputSchema,execute,{mutation=false,risky=false}={})=>({name,title,description,inputSchema,execute,mutation,risky,annotations:{readOnlyHint:!mutation,destructiveHint:risky,untrustedContentHint:!mutation}})
export const codedError=(message,code='invalid_input')=>Object.assign(new Error(message),{code})
export function ensureRevision(store,input){const current=store.bundle?.project?.revision;if(input.expected_revision!==current)throw codedError(`Expected revision ${input.expected_revision}; current revision is ${current}.`,'version_conflict')}
function rememberBounded(map,key,value,maximum=OPERATION_LIMIT){map.set(key,value);while(map.size>maximum)map.delete(map.keys().next().value)}
function activityFor(out){if(out.status==='preview')return['preview','Ready for your approval'];if(out.status==='cancelled')return['cancelled','Change cancelled'];if(out.status==='error')return['error','Observatory paused'];return['ok','Map updated']}

export async function runTool(def,input,options={}){let activityStarted=false;try{if(options.signal?.aborted)throw codedError('The action was cancelled.','cancelled');let validate=validators.get(def.inputSchema);if(!validate){validate=ajv.compile(def.inputSchema);validators.set(def.inputSchema,validate)}if(!validate(input))throw codedError(validate.errors.map((error)=>`${error.instancePath||'input'} ${error.message}`).join('; '));const route=globalThis.location?.pathname||'/',operationKey=input.operation_id?`${route}:${def.name}:${input.operation_id}`:null,canonical=operationKey?stable({route,input:{...input,risk:undefined}}):null;if(operationKey&&operations.has(operationKey)){const prior=operations.get(operationKey);if(prior.canonical!==canonical)throw codedError('This operation_id was already used with different input.','operation_conflict');return prior.output}if(def.mutation){showWebMcpActivity('working','Observatory is working',def.title,0);activityStarted=true}if(def.risky){const risk=input.risk||{};if(risk.preview){const approved=window.confirm(`Allow Observatory to ${def.title.toLowerCase()}?\n\nThe current map revision will be checked again before anything changes.`),out=approved?result('preview',def.name,'The map change is approved and ready to commit.',{preview_token:uuid(),expires_in_seconds:PREVIEW_TTL/1000}):result('cancelled',def.name,'You cancelled the proposed map change.');if(approved)rememberBounded(previews,out.data.preview_token,{canonical,revision:input.expected_revision,expires:Date.now()+PREVIEW_TTL,used:false});const[status,title]=activityFor(out);showWebMcpActivity(status,title,out.message,status==='cancelled'?4000:10000);return out}const approval=previews.get(risk.preview_token);if(!approval||approval.expires<Date.now())throw codedError('Preview approval is missing or expired.','preview_expired');if(approval.used)throw codedError('Preview approval was already used.','preview_consumed');if(approval.canonical!==canonical||approval.revision!==input.expected_revision)throw codedError('The map request changed after approval.','preview_required');approval.used=true}const out=compact(await def.execute(input,options));if(operationKey&&out.status==='ok')rememberBounded(operations,operationKey,{canonical,output:out});if(def.mutation){const[status,title]=activityFor(out);showWebMcpActivity(status,title,out.message)}return out}catch(error){const out=result(error.code==='cancelled'?'cancelled':'error',def.name,error.message,{},error.code||'save_failed');if(def.mutation||activityStarted){const[status,title]=activityFor(out);showWebMcpActivity(status,title,out.message,6000)}return out}}

export function registerScope(name,tools){disposeScope(name);const controller=new AbortController();scopes.set(name,{controller,tools});if(supported())queueMicrotask(()=>tools.forEach((entry)=>Promise.resolve(document.modelContext.registerTool({...entry,execute:(input,options={})=>runTool(entry,input,{...options,signal:options.signal||controller.signal})},{signal:controller.signal})).catch((error)=>{if(!controller.signal.aborted)console.warn('WebMCP registration failed',error)})));return()=>disposeScope(name)}
export function disposeScope(name){scopes.get(name)?.controller.abort();scopes.delete(name)}
