import { expect, test } from '@playwright/test'

async function canvasPoint(page,offsetX=0,offsetY=0){
  const box=await page.locator('.map-viewport').boundingBox()
  return{x:box.x+box.width/2+offsetX,y:box.y+box.height/2+offsetY}
}

async function createBlankMap(page,title){
  await page.goto('/')
  await page.getByRole('button',{name:'New map'}).click()
  await page.getByLabel('Map name').fill(title)
  await page.getByRole('button',{name:'Create map'}).click()
  await expect(page.locator('.map-scene-canvas')).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'Select',exact:true}).click()
  const dismiss=page.getByRole('button',{name:'Dismiss suggestion'})
  if(await dismiss.isVisible())await dismiss.click()
}

test('opens the example in the one-canvas editor and places an object',async({page})=>{
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'Build worlds one tile at a time'})).toBeVisible()
  await expect(page.getByRole('button',{name:'Install app'})).toBeVisible()
  await page.getByRole('button',{name:'More options'}).click()
  await expect(page.getByRole('menuitem',{name:'About and privacy'})).toBeVisible()
  await page.getByRole('button',{name:/Open The Abandoned Tower/}).click()
  await expect(page.locator('.map-scene-canvas')).toBeVisible()
  await expect(page.locator('.terrain-hit-cell')).toHaveCount(0)
  await expect(page.getByRole('application')).toHaveAttribute('aria-label',/terrain marks/)
  await page.getByRole('button',{name:'Place object'}).click()
  await page.getByTitle(/Treasure chest/).click()
  const point=await canvasPoint(page)
  await page.mouse.click(point.x,point.y)
  await expect(page.locator('.scene-selection-box')).toBeVisible()
  await page.getByTitle('Switch theme').click()
  await expect(page.locator('.app-shell')).toHaveClass(/theme-charcoal/)
})

test('keeps placing copies of the selected object until Escape',async({page})=>{
  await createBlankMap(page,'Repeated object placement')
  const center=await canvasPoint(page)
  await page.getByRole('button',{name:'Place object'}).click()
  await page.getByTitle(/Treasure chest/).click()
  await page.mouse.click(center.x-70,center.y)
  await page.mouse.click(center.x+70,center.y)
  await expect(page.getByRole('application')).toHaveAttribute('aria-label',/2 objects/)
  await expect(page.getByRole('button',{name:'Place object'})).toHaveClass(/active/)
  await expect(page.getByTitle(/Treasure chest/)).toHaveClass(/active/)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button',{name:'Select',exact:true})).toHaveClass(/active/)
  await expect(page.getByTitle(/Treasure chest/)).toHaveCount(0)
})

test('describes layers and the fixed map frame in plain language',async({page})=>{
  await createBlankMap(page,'Layer wording')
  await page.getByRole('button',{name:'Toggle layers'}).click()
  await expect(page.getByText('Show or hide parts of your map')).toBeVisible()
  await expect(page.getByText('Painted surfaces')).toBeVisible()
  await expect(page.getByText('Rooms and lines')).toBeVisible()
  await expect(page.getByText('Map frame')).toBeVisible()
  await expect(page.getByText(/cells · .* base · 0 objects/)).toBeVisible()
  await expect(page.getByText('Continuous canvas')).toHaveCount(0)
})

test('keeps the header menu English-only',async({page})=>{
  await page.goto('/')
  await page.getByRole('button',{name:'More options'}).click()
  await expect(page.getByRole('menuitem',{name:'About and privacy'})).toBeVisible()
  await expect(page.getByLabel('Language')).toHaveCount(0)
})

test('promotes the Story Shack ecosystem at natural transition points',async({page})=>{
  await page.goto('/')
  await expect(page.getByRole('link',{name:'A free creative tool from The Story Shack'})).toHaveAttribute('href','https://thestoryshack.com/')
  await expect(page.getByRole('heading',{name:'The map is only the beginning.'})).toBeVisible()
  await expect(page.getByRole('link',{name:/Quarry/})).toHaveAttribute('href','https://quarry.thestoryshack.com/?lang=en')
  await expect(page.getByRole('link',{name:/Junction/})).toHaveAttribute('href','https://junction.thestoryshack.com/?lang=en')
  await expect(page.getByRole('link',{name:/Story Shack/}).last()).toHaveAttribute('href','https://thestoryshack.com/tools/')
  await expect(page.locator('.gateway-app-icon img')).toHaveCount(3)
  await expect(page.locator('.gateway-app-icon img').first()).toHaveAttribute('src','/app-logos/quarry.webp')
  await expect(page.getByRole('link',{name:'Explore all apps'})).toHaveAttribute('href','https://thestoryshack.com/apps/')

  await page.getByRole('button',{name:/Open The Abandoned Tower/}).click()
  await expect(page.locator('.map-scene-canvas')).toBeVisible()
  const download=page.waitForEvent('download')
  await page.getByRole('button',{name:'Export map'}).click()
  await download
  await expect(page.locator('.export-gateway')).toContainText('Where does the story go next')
  await expect(page.locator('.export-gateway').getByRole('link',{name:/Quarry/})).toBeVisible()
  await expect(page.locator('.export-gateway').getByRole('link',{name:/Junction/})).toBeVisible()
})

test('offers an evocative achievable prompt on an empty map',async({page,context})=>{
  await context.grantPermissions(['clipboard-read','clipboard-write'])
  await page.goto('/')
  await page.getByRole('button',{name:'New map'}).click()
  await page.getByLabel('Map name').fill('Prompt study')
  await page.getByRole('button',{name:'Create map'}).click()
  await expect(page.locator('.map-scene-canvas')).toBeVisible({timeout:15000})
  await expect(page.locator('.empty-map-prompt')).toContainText('Build a map of a lone tower in a dense forest.')
  await page.getByRole('button',{name:'Copy prompt'}).click()
  await expect.poll(()=>page.evaluate(()=>navigator.clipboard.readText())).toBe('Build a map of a lone tower in a dense forest.')
  await expect(page.locator('.empty-map-prompt')).toHaveCount(0)
})

test('shows custom tooltips for icon-only navigation and canvas controls',async({page})=>{
  await page.goto('/')
  const theme=page.getByRole('button',{name:'Switch theme'})
  await theme.hover()
  await expect.poll(()=>theme.evaluate((element)=>getComputedStyle(element,'::after').opacity)).toBe('1')
  await page.getByRole('button',{name:/Open The Abandoned Tower/}).click()
  await expect(page.getByRole('application')).toBeVisible()
  for(const control of [page.getByRole('button',{name:'Back to all maps'}),page.getByRole('button',{name:'Fit to canvas'}),page.getByRole('button',{name:'Toggle layers'})]){
    await control.hover()
    await expect.poll(()=>control.evaluate((element)=>getComputedStyle(element,'::after').opacity)).toBe('1')
  }
})

test('shows the exact terrain preview before pointer-up and persists the stroke',async({page})=>{
  await createBlankMap(page,'Live paint study')
  const canvas=page.locator('.map-scene-canvas'),before=await canvas.screenshot()
  await page.getByRole('button',{name:'Paint terrain'}).click()
  await expect(page.getByRole('slider',{name:'Brush diameter'})).toHaveValue('5')
  await expect(page.getByRole('slider',{name:'Brush diameter'})).toHaveAttribute('max','24')
  await page.getByRole('slider',{name:'Brush diameter'}).fill('9')
  await page.getByTitle('Sand').click()
  await page.getByRole('button',{name:'Close'}).focus()
  await page.keyboard.press('Enter')
  const start=await canvasPoint(page,-140,-30),end=await canvasPoint(page,150,55)
  await page.mouse.move(start.x,start.y)
  await expect.poll(async()=>Buffer.compare(await canvas.screenshot(),before)).not.toBe(0)
  await page.mouse.down()
  await page.mouse.move(end.x,end.y,{steps:8})
  const during=await canvas.screenshot()
  expect(Buffer.compare(during,before)).not.toBe(0)
  await page.mouse.up()
  await expect(page.getByText('Saved locally')).toBeVisible()
  await expect(page.getByTitle('Undo')).toBeEnabled()
  expect(Buffer.compare(await canvas.screenshot(),before)).not.toBe(0)
  await page.reload()
  await expect(page.locator('.map-scene-canvas')).toBeVisible()
  await expect(page.getByRole('application')).toHaveAttribute('aria-label',/1 terrain marks/)
})

test('draws a styled text box and supports direct typing',async({page})=>{
  await createBlankMap(page,'Label study')
  const canvas=page.locator('.map-scene-canvas'),beforeLabel=await canvas.screenshot()
  await page.getByRole('button',{name:/Add label/}).click()
  await expect(page.getByLabel('Size',{exact:true})).toHaveCount(0)
  await expect(page.getByLabel('Bold text')).toHaveCount(0)
  await page.getByRole('button',{name:'Cormorant Garamond'}).click()
  await page.getByLabel('Label color').fill('#4f6f52')
  const point=await canvasPoint(page)
  await page.mouse.click(point.x,point.y)
  const editor=page.getByLabel('Map label text')
  await expect(editor).toBeVisible()
  await editor.fill('The Sunken Watch')
  const editorBox=await editor.boundingBox()
  await page.mouse.click(point.x+350,point.y+180)
  await expect(page.getByRole('application')).toHaveAttribute('aria-label',/1 labels/)
  await expect.poll(async()=>Buffer.compare(await canvas.screenshot(),beforeLabel)).not.toBe(0)
  await expect(page.getByRole('button',{name:'Select',exact:true})).toHaveClass(/active/)
  await page.mouse.dblclick(editorBox.x+editorBox.width/2,editorBox.y+editorBox.height/2)
  await expect(page.getByLabel('Map label text')).toHaveValue('The Sunken Watch')
  await page.getByLabel('Map label text').press('Control+Enter')
  await expect(page.getByLabel('Map label text')).toHaveCount(0)
  await page.mouse.click(editorBox.x+editorBox.width/2,editorBox.y+editorBox.height/2)
  const labelSelection=page.locator('.label-selection-box')
  await expect(labelSelection).toBeVisible()
  const beforeResize=await labelSelection.boundingBox(),resize=await page.getByRole('button',{name:'Resize label'}).boundingBox()
  expect(await page.evaluate(({x,y})=>document.elementFromPoint(x,y)?.closest('button')?.getAttribute('aria-label'),{x:resize.x+resize.width/2,y:resize.y+resize.height/2})).toBe('Resize label')
  await page.mouse.move(resize.x+resize.width/2,resize.y+resize.height/2);await page.mouse.down();await page.mouse.move(resize.x+resize.width/2+110,resize.y+resize.height/2+75,{steps:4});await page.mouse.up()
  await expect.poll(async()=>(await labelSelection.boundingBox()).width).toBeGreaterThan(beforeResize.width)
  const beforeRotation=await labelSelection.getAttribute('style'),rotate=await page.getByRole('button',{name:'Rotate label'}).boundingBox()
  await page.mouse.move(rotate.x+rotate.width/2,rotate.y+rotate.height/2);await page.mouse.down();await page.mouse.move(rotate.x-75,rotate.y+65,{steps:4});await page.mouse.up()
  await expect.poll(async()=>labelSelection.getAttribute('style')).not.toBe(beforeRotation)
  const transformedRotation=await labelSelection.evaluate((element)=>element.style.transform)
  const beforeMove=await labelSelection.boundingBox(),moveStart={x:beforeMove.x+beforeMove.width/2,y:beforeMove.y+beforeMove.height/2}
  expect(await page.evaluate(({x,y})=>document.elementFromPoint(x,y)?.classList.contains('label-selection-box'),moveStart)).toBe(true)
  await page.mouse.move(moveStart.x,moveStart.y);await page.mouse.down();await page.mouse.move(moveStart.x+70,moveStart.y+40,{steps:4});await page.mouse.up()
  await expect.poll(async()=>(await labelSelection.boundingBox()).x).toBeGreaterThan(beforeMove.x)
  const movedBox=await labelSelection.boundingBox(),movedCenter={x:movedBox.x+movedBox.width/2,y:movedBox.y+movedBox.height/2}
  await page.getByRole('button',{name:'Edit label'}).click()
  await expect(page.getByLabel('Selected label text')).toHaveCount(0)
  await expect(page.getByLabel('Selected label size')).toHaveCount(0)
  await expect(page.getByLabel('Bold text')).toHaveCount(0)
  await expect(page.getByRole('button',{name:'Use Cormorant Garamond'})).toHaveAttribute('aria-pressed','true')
  await expect(page.getByLabel('Selected label color')).toHaveValue('#4f6f52')
  await page.getByRole('button',{name:'Use IM FELL English'}).click()
  await expect(page.getByRole('button',{name:'Use IM FELL English'})).toHaveAttribute('aria-pressed','true')
  await page.reload()
  await expect(page.getByRole('application')).toHaveAttribute('aria-label',/1 labels/)
  await page.getByRole('button',{name:'Select',exact:true}).click()
  await page.mouse.click(movedCenter.x,movedCenter.y)
  await expect(page.locator('.label-selection-box')).toHaveCSS('transform',/matrix/)
  await expect.poll(async()=>page.locator('.label-selection-box').evaluate((element)=>element.style.transform)).toBe(transformedRotation)
  await expect.poll(async()=>(await page.locator('.label-selection-box').boundingBox()).width).toBeGreaterThan(beforeResize.width)
})

test('keeps and saves label text when the map changed in another tab',async({page,context})=>{
  await createBlankMap(page,'Concurrent label study')
  const otherPage=await context.newPage()
  await otherPage.goto(page.url())
  await expect(otherPage.locator('.map-scene-canvas')).toBeVisible({timeout:15000})
  await otherPage.getByRole('button',{name:'Dismiss suggestion'}).click()
  await otherPage.getByRole('button',{name:/Add label/}).click()
  const otherPoint=await canvasPoint(otherPage,180,90)
  await otherPage.mouse.click(otherPoint.x,otherPoint.y)
  await otherPage.getByLabel('Map label text').fill('From the other tab')
  await otherPage.getByLabel('Map label text').press('Control+Enter')
  await expect(otherPage.getByRole('application')).toHaveAttribute('aria-label',/1 labels/)

  await page.getByRole('button',{name:/Add label/}).click()
  const point=await canvasPoint(page)
  await page.mouse.click(point.x,point.y)
  const editor=page.getByLabel('Map label text')
  await editor.fill('Still here')
  await page.mouse.click(point.x+350,point.y+180)

  await expect(page.getByRole('application')).toHaveAttribute('aria-label',/2 labels/)
  await expect(editor).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('application')).toHaveAttribute('aria-label',/2 labels/)
  await otherPage.close()
})

test('discards an interrupted terrain gesture instead of saving a stuck stroke',async({page})=>{
  await createBlankMap(page,'Interrupted paint study')
  await page.getByRole('button',{name:'Paint terrain'}).click()
  const start=await canvasPoint(page,-120,-30),end=await canvasPoint(page,130,45)
  await page.mouse.move(start.x,start.y)
  await page.mouse.down()
  await page.mouse.move(end.x,end.y,{steps:6})
  await page.evaluate(()=>window.dispatchEvent(new Event('blur')))
  await page.mouse.up()
  await expect(page.getByRole('application')).toHaveAttribute('aria-label',/0 terrain marks/)
  await expect(page.getByTitle('Undo')).toBeDisabled()
})

test('draws clipped rooms and connected wall paths without cell sections',async({page})=>{
  await createBlankMap(page,'Structure study')
  const canvas=page.locator('.map-scene-canvas'),before=await canvas.screenshot()
  await page.getByRole('button',{name:'Draw shape'}).click()
  await page.getByRole('button',{name:'Close',exact:true}).click()
  const roomStart=await canvasPoint(page,-130,-90),roomEnd=await canvasPoint(page,80,75)
  await page.mouse.move(roomStart.x,roomStart.y);await page.mouse.down();await page.mouse.move(roomEnd.x,roomEnd.y,{steps:5})
  await expect(page.locator('.scene-room-size')).toBeVisible()
  await page.mouse.up()
  await expect.poll(async()=>Buffer.compare(await canvas.screenshot(),before)).not.toBe(0)
  await page.getByRole('button',{name:'Draw lines'}).click()
  await expect(page.getByRole('button',{name:/Stone wall/})).toHaveAttribute('aria-pressed','true')
  await expect(page.getByLabel('Line width')).toHaveValue('0.52')
  await page.getByRole('button',{name:/Palisade/}).click()
  await expect(page.getByLabel('Line width')).toHaveValue('0.52')
  await page.getByLabel('Line width').fill('0.7')
  const wallStart=await canvasPoint(page,-180,120),wallEnd=await canvasPoint(page,180,130),afterRoom=await canvas.screenshot()
  await page.mouse.move(wallStart.x,wallStart.y);await page.mouse.down();await page.mouse.move(wallEnd.x,wallEnd.y,{steps:10});await page.mouse.up()
  await expect.poll(async()=>Buffer.compare(await canvas.screenshot(),afterRoom)).not.toBe(0)
  await expect(page.locator('.map-structure')).toHaveCount(0)
  const download=page.waitForEvent('download')
  await page.getByRole('button',{name:'Export'}).click()
  expect((await download).suggestedFilename()).toBe('structure-study.png')
})

test('creates, selects, edits, and removes shaped rooms',async({page})=>{
  await createBlankMap(page,'Editable room study')
  await page.getByRole('button',{name:'Draw shape'}).click()
  await expect(page.getByLabel('Shape wall type')).toHaveCount(0)
  await page.getByRole('button',{name:'Use Star shape'}).click()
  await page.getByLabel('Shape points').fill('7')
  await page.getByRole('button',{name:'Use Hedge',exact:true}).click()
  await page.getByRole('button',{name:'Use Wooden planks floor texture'}).click()
  await page.getByRole('button',{name:'Close'}).click()
  const center=await canvasPoint(page),start={x:center.x-100,y:center.y-70},end={x:center.x+100,y:center.y+70}
  await page.keyboard.down('Shift');await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(end.x,end.y,{steps:6});await page.mouse.up();await page.keyboard.up('Shift')
  await expect(page.locator('.room-selection-box')).toBeVisible()
  await expect(page.getByRole('button',{name:'Bring shape to front'})).toBeVisible()
  await page.getByRole('button',{name:'Bring shape to front'}).click()
  await page.getByRole('button',{name:'Edit shape'}).click()
  await expect(page.getByLabel('Selected shape type')).toHaveValue('star')
  await expect(page.getByLabel('Selected shape points')).toHaveValue('7')
  await expect(page.getByLabel('Selected shape wall type')).toHaveValue('hedge')
  await expect(page.getByLabel('Shape fill texture')).toHaveValue('wood')
  await expect(page.getByLabel('Shape wall thickness')).toHaveValue('0.64')
  await page.getByLabel('Shape wall thickness').fill('0.9')
  await expect(page.getByLabel('Shape width')).toHaveCount(0)
  await expect(page.getByLabel('Shape height')).toHaveCount(0)
  await expect(page.getByLabel('Shape rotation')).toHaveCount(0)
  await page.getByLabel('Selected shape type').selectOption('ellipse')
  await page.getByRole('button',{name:'Close'}).click()
  const selection=page.locator('.room-selection-box'),beforeResize=await selection.boundingBox(),resize=await page.getByRole('button',{name:'Resize shape'}).boundingBox()
  await page.mouse.move(resize.x+resize.width/2,resize.y+resize.height/2);await page.mouse.down();await page.mouse.move(resize.x+55,resize.y+55,{steps:4});await page.mouse.up()
  await expect.poll(async()=>(await selection.boundingBox()).width).toBeGreaterThan(beforeResize.width)
  const beforeRotation=await selection.getAttribute('style'),rotate=await page.getByRole('button',{name:'Rotate shape'}).boundingBox()
  await page.mouse.move(rotate.x+rotate.width/2,rotate.y+rotate.height/2);await page.mouse.down();await page.mouse.move(rotate.x-80,rotate.y+70,{steps:4});await page.mouse.up()
  await expect.poll(async()=>selection.getAttribute('style')).not.toBe(beforeRotation)
  const transformedRotation=await selection.evaluate((element)=>element.style.transform)
  await expect(page.getByText('Saved locally')).toBeVisible()
  await page.reload()
  await expect(page.locator('.map-scene-canvas')).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'Select'}).click()
  await page.mouse.click(center.x,center.y)
  await expect(page.locator('.room-selection-box')).toBeVisible()
  await expect.poll(async()=>page.locator('.room-selection-box').evaluate((element)=>element.style.transform)).toBe(transformedRotation)
  await expect(page.getByLabel('Shape wall thickness')).toHaveValue('0.9')
  await expect(page.getByRole('button',{name:'Resize shape'})).toBeVisible()
  await expect(page.getByRole('button',{name:'Rotate shape'})).toBeVisible()
  await page.getByRole('button',{name:'Remove shape'}).click()
  await expect(page.locator('.room-selection-box')).toHaveCount(0)
})

test('supports object transforms, dragging, deletion, zoom, and brush-sized erasing',async({page})=>{
  await createBlankMap(page,'Interaction study')
  const center=await canvasPoint(page)
  await page.getByRole('button',{name:'Place object'}).click()
  await page.getByTitle(/Leafy tree/).click()
  await page.mouse.click(center.x,center.y)
  const selection=page.locator('.scene-selection-box')
  await expect(selection).toBeVisible()
  const beforeResize=await selection.boundingBox(),resize=await page.getByRole('button',{name:'Resize object'}).boundingBox()
  await page.mouse.move(resize.x+resize.width/2,resize.y+resize.height/2);await page.mouse.down();await page.mouse.move(resize.x+55,resize.y+55,{steps:4});await page.mouse.up()
  await expect.poll(async()=>(await selection.boundingBox()).width).toBeGreaterThan(beforeResize.width)
  await page.getByRole('button',{name:'Select'}).click()
  const canvas=page.locator('.map-scene-canvas'),beforeMove=await canvas.screenshot()
  await page.mouse.move(center.x,center.y);await page.mouse.down();await page.mouse.move(center.x+70,center.y+35,{steps:5})
  await expect.poll(async()=>Buffer.compare(await canvas.screenshot(),beforeMove)).not.toBe(0)
  await page.mouse.up()
  await expect(selection).toBeVisible()
  await page.keyboard.press('Backspace')
  await expect(selection).toHaveCount(0)
  const zoom=page.locator('.zoom-value'),beforeZoom=await zoom.textContent()
  await page.keyboard.press('Control+=');await expect(zoom).not.toHaveText(beforeZoom)
  await page.keyboard.press('Control+-');await expect(zoom).toHaveText(beforeZoom)
  await page.getByRole('button',{name:'Erase'}).click()
  await page.getByRole('slider',{name:'Brush diameter'}).fill('8')
  const sizeControl=page.locator('.brush-control').filter({has:page.getByRole('slider',{name:'Brush diameter'})})
  await expect(sizeControl.locator('output')).toHaveText('8 cells')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button',{name:'Select',exact:true})).toHaveClass(/active/)
})

test('keeps a new rectangular object footprint aligned while rotating',async({page})=>{
  await createBlankMap(page,'Object footprint study')
  const center=await canvasPoint(page)
  await page.getByRole('button',{name:'Place object'}).click()
  await page.getByTitle(/Rowboat/).click()
  await page.mouse.click(center.x,center.y)
  const selection=page.locator('.scene-selection-box'),before=await selection.boundingBox()
  expect(before.height).toBeGreaterThan(before.width*1.7)
  const rotate=await page.getByRole('button',{name:'Rotate object'}).boundingBox()
  await page.mouse.move(rotate.x+rotate.width/2,rotate.y+rotate.height/2)
  await page.mouse.down()
  await page.mouse.move(center.x+before.height/2,center.y,{steps:6})
  await page.mouse.up()
  const after=await selection.boundingBox()
  expect(after.width).toBeGreaterThan(after.height)
})

test('keeps terrain and object picker atlases on their own grid sizes',async({page})=>{
  await createBlankMap(page,'Atlas preview study')
  await page.getByRole('button',{name:'Paint terrain'}).click()
  const terrain=page.getByTitle('Dungeon stone').locator('.terrain-swatch')
  await expect(terrain).toHaveCSS('background-size','400% 400%')
  await expect(terrain).toHaveCSS('background-position','33.3333% 0%')
  await page.getByRole('button',{name:'Place object'}).click()
  const object=page.getByTitle(/Rowboat/).locator('.object-swatch')
  await expect(object).toHaveCSS('background-size','500% 500%')
  await expect(object).toHaveCSS('background-position','75% 100%')
})

test('keeps separate paint and eraser softness defaults',async({page})=>{
  await createBlankMap(page,'Softness study')
  await page.getByRole('button',{name:'Paint terrain'}).click()
  await expect(page.getByRole('slider',{name:'Brush softness'})).toHaveValue('100')
  await page.getByRole('button',{name:'Erase'}).click()
  const eraserSoftness=page.getByRole('slider',{name:'Eraser softness'})
  await expect(eraserSoftness).toHaveValue('0')
  await eraserSoftness.fill('35')
  await page.getByRole('button',{name:'Paint terrain'}).click()
  await expect(page.getByRole('slider',{name:'Brush softness'})).toHaveValue('100')
})

test('copies and repeatedly pastes selected objects with visible offsets',async({page})=>{
  await createBlankMap(page,'Copy paste study')
  const center=await canvasPoint(page)
  await page.getByRole('button',{name:'Place object'}).click()
  await page.getByTitle(/Treasure chest/).click()
  await page.getByRole('button',{name:'Close'}).click()
  await page.mouse.click(center.x,center.y)
  await page.getByRole('button',{name:'Select'}).click()
  await page.mouse.click(center.x,center.y)
  const selection=page.locator('.scene-selection-box'),original=await selection.boundingBox()
  await page.keyboard.press('Control+c');await page.keyboard.press('Control+v')
  await expect(page.getByRole('application')).toHaveAttribute('aria-label',/2 objects/)
  await expect.poll(async()=>(await selection.boundingBox()).x).toBeGreaterThan(original.x)
  const firstCopy=await selection.boundingBox()
  await page.keyboard.press('Control+v')
  await expect(page.getByRole('application')).toHaveAttribute('aria-label',/3 objects/)
  await expect.poll(async()=>(await selection.boundingBox()).x).toBeGreaterThan(firstCopy.x)
})

test('deselects an object when the empty canvas is clicked',async({page})=>{
  await createBlankMap(page,'Selection study')
  const center=await canvasPoint(page)
  await page.getByRole('button',{name:'Place object'}).click()
  await page.getByTitle(/Treasure chest/).click()
  await page.getByRole('button',{name:'Close'}).click()
  await page.mouse.click(center.x,center.y)
  await page.getByRole('button',{name:'Select'}).click()
  await page.mouse.click(center.x,center.y)
  await expect(page.locator('.scene-selection-box')).toBeVisible()
  await expect(page.locator('.dock-tool[aria-label="Select"]')).toHaveClass(/active/)
  await page.mouse.click(center.x+180,center.y+120)
  await expect(page.locator('.scene-selection-box')).toHaveCount(0)
  await expect(page.getByRole('application')).toHaveAttribute('aria-label',/1 objects/)
})

test('supports temporary Space panning and keyboard history shortcuts',async({page})=>{
  await createBlankMap(page,'Keyboard study')
  const center=await canvasPoint(page),canvas=page.locator('.map-scene-canvas')
  await page.getByRole('button',{name:'Place object'}).click()
  await page.getByTitle(/Treasure chest/).click()
  await page.mouse.click(center.x,center.y)
  await expect(page.getByRole('application')).toHaveAttribute('aria-label',/1 objects/)
  await page.keyboard.press('Control+z')
  await expect(page.getByRole('application')).toHaveAttribute('aria-label',/0 objects/)
  await page.keyboard.press('Control+y')
  await expect(page.getByRole('application')).toHaveAttribute('aria-label',/1 objects/)

  // Non-text controls retain focus after use; they must not disable canvas shortcuts.
  await page.getByRole('button',{name:'Paint terrain'}).click()
  const brushSize=page.getByRole('slider',{name:'Brush diameter'})
  await brushSize.focus()
  await page.keyboard.press('Control+z')
  await expect(page.getByRole('application')).toHaveAttribute('aria-label',/0 objects/)
  await page.keyboard.press('Control+y')
  await expect(page.getByRole('application')).toHaveAttribute('aria-label',/1 objects/)

  await page.keyboard.press('v')
  await expect(page.getByRole('button',{name:'Select'})).toHaveClass(/active/)
  const zoom=page.locator('.zoom-value'),beforeWheel=await zoom.textContent()
  await page.mouse.move(center.x,center.y);await page.mouse.wheel(0,-180)
  await expect(zoom).not.toHaveText(beforeWheel)
  await page.getByRole('button',{name:'Paint terrain'}).click()
  await brushSize.focus()
  const beforePan=await canvas.screenshot()
  await page.keyboard.down('Space')
  await page.mouse.move(center.x,center.y);await page.mouse.down();await page.mouse.move(center.x+110,center.y+70,{steps:5});await page.mouse.up()
  await page.keyboard.up('Space')
  expect(Buffer.compare(await canvas.screenshot(),beforePan)).not.toBe(0)
  await expect(page.getByRole('button',{name:'Paint terrain'})).toHaveClass(/active/)

  const beforeTrackpadPan=await canvas.screenshot(),zoomBeforeTrackpadPan=await zoom.textContent()
  await page.keyboard.down('Space')
  await page.mouse.move(center.x,center.y);await page.mouse.wheel(90,60)
  await page.keyboard.up('Space')
  expect(Buffer.compare(await canvas.screenshot(),beforeTrackpadPan)).not.toBe(0)
  await expect(zoom).toHaveText(zoomBeforeTrackpadPan)

  const beforeSecondaryPan=await canvas.screenshot()
  await page.keyboard.down('Space')
  const contextMenuPrevented=await page.getByRole('application').evaluate((element)=>!element.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true,button:2})))
  expect(contextMenuPrevented).toBe(true)
  await page.mouse.move(center.x,center.y);await page.mouse.down({button:'right'});await page.mouse.move(center.x-90,center.y-60,{steps:5});await page.mouse.up({button:'right'})
  await page.keyboard.up('Space')
  expect(Buffer.compare(await canvas.screenshot(),beforeSecondaryPan)).not.toBe(0)
})

test('switches tools with single-key shortcuts without hijacking text entry',async({page})=>{
  await createBlankMap(page,'Tool shortcuts')
  const shortcuts=[['b','Paint terrain'],['s','Draw shape'],['l','Draw lines'],['o','Place object'],['t','Add label'],['e','Erase'],['i','Pick from map'],['v','Select']]
  for(const [key,name] of shortcuts){await page.keyboard.press(key);await expect(page.getByRole('button',{name})).toHaveClass(/active/)}
  await page.keyboard.press('t')
  const point=await canvasPoint(page)
  await page.mouse.click(point.x,point.y)
  const input=page.getByRole('textbox',{name:'Map label text'})
  await input.fill('vital')
  await page.keyboard.press('v')
  await expect(input).toHaveValue('vitalv')
  await expect(page.getByRole('button',{name:'Add label'})).toHaveClass(/active/)
})

test('shows shortcut keycaps and a reference in More options',async({page})=>{
  await createBlankMap(page,'Shortcut reference')
  await expect(page.locator('.tool-dock .dock-shortcut')).toHaveText(['V','I','B','S','L','O','T','E'])
  await page.getByRole('button',{name:'More options'}).click()
  await page.getByRole('menuitem',{name:'Keyboard shortcuts'}).click()
  const dialog=page.getByRole('dialog',{name:'Keyboard shortcuts'})
  await expect(dialog).toBeVisible()
  await expect(dialog.locator('.shortcut-list')).toContainText('Temporarily pan')
  await expect(dialog.locator('kbd')).toHaveText(['V','I','B','S','L','O','T','E','Space','⌘/Ctrl Z','⌘/Ctrl ⇧ Z'])
  await page.getByRole('button',{name:'Close shortcuts'}).click()
  await expect(dialog).toBeHidden()
})

test('moves the Lines panel with the shared drag handle',async({page})=>{
  await createBlankMap(page,'Draggable lines panel')
  await page.getByRole('button',{name:'Draw lines'}).click()
  const panel=page.locator('.asset-panel'),handle=panel.locator('.picker-drag-handle')
  await expect(handle).toBeVisible()
  await expect(handle.locator('.picker-grip')).toBeVisible()
  const before=await panel.boundingBox(),drag=await handle.boundingBox()
  await page.mouse.move(drag.x+drag.width/2,drag.y+drag.height/2)
  await page.mouse.down()
  await page.mouse.move(drag.x+drag.width/2+90,drag.y+drag.height/2-45,{steps:5})
  await page.mouse.up()
  const after=await panel.boundingBox()
  expect(after.x).toBeGreaterThan(before.x+70)
  expect(after.y).toBeLessThan(before.y-25)
})

test('moves the Text style panel with the shared drag handle',async({page})=>{
  await createBlankMap(page,'Draggable text style panel')
  await page.getByRole('button',{name:'Add label'}).click()
  const panel=page.locator('.label-panel'),handle=panel.locator('.picker-drag-handle')
  await expect(handle).toBeVisible()
  await expect(handle.locator('.picker-grip')).toBeVisible()
  const before=await panel.boundingBox(),drag=await handle.boundingBox()
  await page.mouse.move(drag.x+drag.width/2,drag.y+drag.height/2)
  await page.mouse.down()
  await page.mouse.move(drag.x+drag.width/2+100,drag.y+drag.height/2-55,{steps:5})
  await page.mouse.up()
  const after=await panel.boundingBox()
  expect(after.x).toBeGreaterThan(before.x+80)
  expect(after.y).toBeLessThan(before.y-35)
})

test('keeps line width when switching line types',async({page})=>{
  await createBlankMap(page,'Persistent line width')
  await page.getByRole('button',{name:'Draw lines'}).click()
  const width=page.getByRole('slider',{name:'Line width'})
  await width.fill('1.1')
  await page.getByRole('button',{name:/Cliff edge/}).click()
  await expect(width).toHaveValue('1.1')
  await page.getByRole('button',{name:/Hedge/}).click()
  await expect(width).toHaveValue('1.1')
})

test('picks terrain, lines, and objects directly from the map',async({page})=>{
  await createBlankMap(page,'Eyedropper study')
  expect(await page.locator('.view-controls>.icon-button').evaluateAll((controls)=>controls.map((control)=>control.getAttribute('aria-label')))).toEqual(['Zoom out','Zoom in','Fit to canvas','Toggle grid','Toggle layers'])
  expect(await page.locator('.tool-dock>.dock-tool').evaluateAll((tools)=>tools.map((tool)=>tool.title))).toEqual(['Select (V)','Pick from map (I)','Paint terrain (B)','Draw shape (S)','Draw lines (L)','Place object (O)','Add label (T)','Erase (E)'])
  await expect(page.locator('.tool-dock>.dock-tool small')).toHaveText(['Select','Pick','Terrain','Shapes','Lines','Objects','Labels','Erase'])
  const center=await canvasPoint(page),objectPoint={x:center.x+150,y:center.y}
  await page.getByRole('button',{name:'Paint terrain'}).click()
  await page.getByRole('slider',{name:'Brush diameter'}).fill('9')
  await page.getByRole('slider',{name:'Brush softness'}).fill('35')
  await page.getByTitle('Sand').click()
  await page.getByRole('button',{name:'Close'}).click()
  await page.mouse.move(center.x-80,center.y);await page.mouse.down();await page.mouse.move(center.x+60,center.y,{steps:5});await page.mouse.up()
  await page.getByRole('button',{name:'Place object'}).click()
  await page.getByTitle(/Treasure chest/).click()
  await page.getByRole('button',{name:'Close'}).click()
  await page.mouse.click(objectPoint.x,objectPoint.y)

  await page.getByRole('button',{name:'Pick from map'}).click()
  await page.mouse.click(objectPoint.x,objectPoint.y)
  await expect(page.getByRole('button',{name:'Place object'})).toHaveClass(/active/)
  await page.getByRole('button',{name:'Place object'}).click()
  await expect(page.getByTitle(/Treasure chest/)).toHaveClass(/active/)

  await page.getByRole('button',{name:'Pick from map'}).click()
  await page.getByRole('button',{name:'Paint terrain'}).click()
  await page.getByRole('slider',{name:'Brush diameter'}).fill('3')
  await page.getByRole('slider',{name:'Brush softness'}).fill('100')
  await page.getByRole('button',{name:'Close'}).click()
  await page.getByRole('button',{name:'Pick from map'}).click()
  await page.mouse.click(center.x,center.y)
  await expect(page.getByRole('button',{name:'Paint terrain'})).toHaveClass(/active/)
  await page.getByRole('button',{name:'Paint terrain'}).click()
  await expect(page.getByTitle('Sand')).toHaveClass(/active/)
  await expect(page.getByRole('slider',{name:'Brush diameter'})).toHaveValue('9')
  await expect(page.getByRole('slider',{name:'Brush softness'})).toHaveValue('35')

  const lineStart={x:center.x-100,y:center.y+110},lineEnd={x:center.x+100,y:center.y+110}
  await page.getByRole('button',{name:'Draw lines'}).click()
  await page.getByRole('button',{name:/Palisade/}).click()
  await page.getByRole('slider',{name:'Line width'}).fill('0.88')
  await page.getByRole('button',{name:'Close',exact:true}).click()
  await page.mouse.move(lineStart.x,lineStart.y);await page.mouse.down();await page.mouse.move(lineEnd.x,lineEnd.y,{steps:6});await page.mouse.up()
  await page.getByRole('button',{name:'Pick from map'}).click()
  await page.mouse.click(center.x,center.y+110)
  await expect(page.getByRole('button',{name:'Draw lines'})).toHaveClass(/active/)
  await page.getByRole('button',{name:'Draw lines'}).click()
  await expect(page.getByRole('button',{name:/Palisade/})).toHaveAttribute('aria-pressed','true')
  await expect(page.getByRole('slider',{name:'Line width'})).toHaveValue('0.88')
})

test('keeps the continuous editor and tools usable on mobile',async({page})=>{
  await page.setViewportSize({width:390,height:844})
  await page.goto('/')
  await page.evaluate(()=>localStorage.setItem('observatory-picker-positions',JSON.stringify({terrain:{x:700,y:700},room:{x:700,y:700}})))
  await page.getByRole('button',{name:/Open The Abandoned Tower/}).click()
  await expect(page.locator('.map-scene-canvas')).toBeVisible()
  const toolbar=page.getByRole('navigation',{name:'Map tools'})
  await expect(toolbar).toBeVisible()
  await expect(page.getByRole('button',{name:'Select'})).toBeVisible()
  await expect(page.getByRole('button',{name:'Erase'})).toBeVisible()
  const toolbarMetrics=await toolbar.evaluate((element)=>{const bounds=element.getBoundingClientRect();return{fits:element.scrollWidth<=element.clientWidth,left:bounds.left,right:bounds.right,height:bounds.height}})
  expect(toolbarMetrics).toMatchObject({fits:true})
  expect(toolbarMetrics.left).toBeGreaterThanOrEqual(0)
  expect(toolbarMetrics.right).toBeLessThanOrEqual(390)
  expect(toolbarMetrics.height).toBeGreaterThan(90)
  await page.getByRole('button',{name:'Paint terrain'}).click()
  await expect(page.getByTitle('Worn stone')).toBeVisible()
  await expect(page.getByRole('slider',{name:'Brush diameter'})).toBeVisible()
  const assertPanelFitsAboveToolbar=async(selector)=>{
    const panelBounds=await page.locator(selector).boundingBox()
    const toolbarBounds=await toolbar.boundingBox()
    expect(panelBounds.x).toBeGreaterThanOrEqual(0)
    expect(panelBounds.x+panelBounds.width).toBeLessThanOrEqual(390)
    expect(panelBounds.y).toBeGreaterThanOrEqual(0)
    expect(panelBounds.y+panelBounds.height).toBeLessThanOrEqual(toolbarBounds.y)
  }
  await assertPanelFitsAboveToolbar('.asset-panel')
  await expect(page.locator('.asset-panel .picker-grip')).toBeHidden()
  await page.getByRole('button',{name:'Draw shape'}).click()
  await expect(page.getByLabel('Shape wall type')).toHaveCount(0)
  await expect(page.getByRole('button',{name:'Use Star shape'})).toBeVisible()
  await expect(page.getByRole('button',{name:'Use Wooden planks floor texture'})).toBeVisible()
  await expect(page.getByRole('button',{name:'Use Hedge',exact:true})).toBeVisible()
  await assertPanelFitsAboveToolbar('.shape-panel')
})
