<script setup>
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import AppHeader from '../components/AppHeader.vue'
import { useWorkspaceStore } from '../stores/workspace.js'
import { importObservatory } from '../services/portability.js'

const store = useWorkspaceStore(), router = useRouter(), showCreate = ref(false), title = ref(''), premise = ref(''), showArchived = ref(false), input = ref()
const visibleProjects = computed(() => store.projects.filter((p) => Boolean(p.archivedAt) === showArchived.value && !p.deletedAt))
async function create() { const project = await store.createNewProject({ title: title.value, premise: premise.value }); showCreate.value = false; title.value = ''; premise.value = ''; router.push(`/observatory/${project.id}`) }
async function open(id) { router.push(`/observatory/${id}`) }
async function rename(project) { const value = prompt('Name this observatory', project.title); if (value?.trim()) await store.patchProject(project.id, { title: value.trim() }) }
async function importFile(event) { const file = event.target.files?.[0]; if (!file) return; const project = await importObservatory(file); await store.refreshProjects(); router.push(`/observatory/${project.id}`); event.target.value = '' }
async function requestStorage() { if (navigator.storage?.persist) await navigator.storage.persist(); }
</script>
<template><main class="library-page"><AppHeader/><section class="library-hero"><h1>{{ $t('brand') }}</h1><p>{{ $t('tagline') }}</p></section><section class="library-toolbar"><div><h2>{{ showArchived ? $t('archive') : $t('library') }}</h2><button class="button" @click="showArchived=!showArchived">{{ showArchived ? $t('library') : $t('archive') }}</button></div><div class="library-actions"><input ref="input" hidden type="file" accept=".observatory" @change="importFile"><button class="button" @click="input.click()">{{ $t('import') }}</button><button class="button" @click="requestStorage">{{ $t('requestStorage') }}</button><button class="button primary" @click="showCreate=true">{{ $t('newProject') }}</button></div></section><section class="project-grid"><article v-for="project in visibleProjects" :key="project.id" class="project-card"><button class="project-sky" style="border:0;width:100%;cursor:pointer" :aria-label="`${$t('open')} ${project.title}`" @click="open(project.id)"></button><div class="project-card-body"><h3>{{ project.title }}</h3><p>{{ project.premise || $t('emptyLibrary') }}</p><div class="project-meta"><span>Revision {{ project.revision }}</span><span>{{ new Date(project.updatedAt).toLocaleDateString() }}</span></div><div class="project-menu"><button class="button primary" @click="open(project.id)">{{ $t('open') }}</button><button class="button" @click="rename(project)">{{ $t('rename') }}</button><button class="button" @click="store.duplicateProject(project.id)">{{ $t('duplicate') }}</button><button v-if="!showArchived" class="button" @click="store.patchProject(project.id,{archivedAt:new Date().toISOString()})">{{ $t('archive') }}</button><button v-else class="button" @click="store.patchProject(project.id,{archivedAt:null})">{{ $t('restore') }}</button><button class="button danger" @click="store.patchProject(project.id,{deletedAt:new Date().toISOString()})">{{ $t('delete') }}</button></div></div></article><div v-if="!visibleProjects.length" class="empty-state"><h3>{{ showArchived ? $t('archiveEmpty') : $t('emptyLibrary') }}</h3><button v-if="!showArchived" class="button primary" @click="showCreate=true">{{ $t('startBlank') }}</button></div></section>
<div v-if="showCreate" class="modal-backdrop" @click.self="showCreate=false"><form class="modal" @submit.prevent="create"><h2>{{ $t('newProject') }}</h2><div class="field"><label>{{ $t('title') }}</label><input v-model="title" required maxlength="200" autofocus></div><div class="field"><label>{{ $t('premise') }}</label><textarea v-model="premise" maxlength="20000"></textarea></div><div class="modal-actions"><button type="button" class="button" @click="showCreate=false">{{ $t('cancel') }}</button><button class="button primary">{{ $t('create') }}</button></div></form></div></main></template>
