<script setup>
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { VueFlow, useVueFlow } from '@vue-flow/core'
import { Background } from '@vue-flow/background'
import { Controls } from '@vue-flow/controls'
import { MiniMap } from '@vue-flow/minimap'
import AppHeader from '../components/AppHeader.vue'
import StoryNode from '../components/StoryNode.vue'
import CardInspector from '../components/CardInspector.vue'
import { CARD_TYPES, TYPE_MAP } from '../constants.js'
import { useWorkspaceStore } from '../stores/workspace.js'
import { exportArchive, exportMarkdown, exportPng } from '../services/portability.js'

const props=defineProps({id:String}),store=useWorkspaceStore(),router=useRouter(),search=ref(''),tab=ref('inspect'),showExport=ref(false),showTrash=ref(false),canvas=ref(),confirmDelete=ref(null)
const flow=useVueFlow()
const nodes=computed(()=>store.activeCards.filter(matches).map(card=>({id:card.id,type:'story',position:card.position,data:{...card,typeLabel:card.typeId,color:card.color||TYPE_MAP[card.typeId]?.color}})))
const edges=computed(()=>store.activeRelationships.map(rel=>({id:rel.id,source:rel.source,target:rel.target,label:rel.label,style:{stroke:rel.color},markerEnd:rel.direction==='forward'?'arrowclosed':undefined})))
const trashed=computed(()=>[...(store.bundle?.cards||[]),...(store.bundle?.relationships||[]),...(store.bundle?.groups||[])].filter(x=>x.deletedAt))
function matches(card){const q=search.value.trim().toLowerCase();return !q||[card.title,card.body,card.typeId,...(card.tags||[])].some(x=>String(x||'').toLowerCase().includes(q))}
async function add(typeId){await store.addCards([{typeId,title:`Untitled ${typeId}`}]);setTimeout(()=>flow.fitView({padding:.18,duration:300}),0)}
async function connect(connection){await store.connectCards([{source:connection.source,target:connection.target,label:'influences'}])}
async function move({node}){await store.updateCards([{id:node.id,position:node.position}])}
function askDelete(id){confirmDelete.value=[id]}
async function remove(){await store.deleteElements(confirmDelete.value);confirmDelete.value=null}
async function restore(item){await store.commit((draft)=>{for(const key of ['cards','relationships','groups']){const found=draft[key].find(x=>x.id===item.id);if(found)found.deletedAt=null}})}
function focusLens(lens){store.select(lens.elementIds);flow.fitView({nodes:lens.elementIds,padding:.4,duration:300})}
async function performExport(kind){if(kind==='archive')await exportArchive(store.bundle);if(kind==='markdown')exportMarkdown(store.bundle);if(kind==='png')await exportPng(canvas.value,store.bundle);showExport.value=false}
watch(()=>props.id,async id=>{if(!await store.openProject(id))router.replace('/')},{immediate:true})
watch(()=>store.selection,(ids)=>flow.setNodes(nodes.value.map(n=>({...n,selected:ids.includes(n.id)}))),{deep:true})
onMounted(()=>window.addEventListener('keydown',keyHandler))
onBeforeUnmount(()=>window.removeEventListener('keydown',keyHandler))
function keyHandler(e){if((e.metaKey||e.ctrlKey)&&e.key==='z'){e.preventDefault();e.shiftKey?store.redo():store.undo()}if(e.key==='Delete'&&store.selection.length)askDelete(store.selection)}
</script>
<template><main v-if="store.bundle" class="workspace-page"><AppHeader workspace @export="showExport=true" @trash="showTrash=true"/><div v-if="store.externalRevision" class="agent-toast" style="bottom:auto;top:80px"><span>!</span><div><strong>{{ $t('externalChange') }}</strong><p>Revision {{ store.externalRevision }}</p></div><button @click="store.openProject(id)">↻</button></div><section class="workspace"><aside class="palette"><div class="panel-heading"><h2>{{ $t('palette') }}</h2></div><input v-model="search" class="search-input" :placeholder="$t('search')"><div class="type-list"><button v-for="type in CARD_TYPES" :key="type.id" class="type-button" :style="{'--type-color':type.color}" @click="add(type.id)"><span class="type-dot"></span>{{ $t('addCard',{type:type.id}) }}</button></div></aside><section ref="canvas" class="canvas-wrap"><div class="canvas-toolbar"><button class="button" @click="store.arrange('constellation')">{{ $t('constellation') }}</button><button class="button" @click="store.arrange('story_flow')">{{ $t('storyFlow') }}</button><button class="button" @click="store.arrange('tidy',store.selection)">{{ $t('tidy') }}</button></div><VueFlow :nodes="nodes" :edges="edges" fit-view-on-init :min-zoom=".2" :max-zoom="2" multi-selection-key-code="Shift" @node-click="store.select([$event.node.id])" @pane-click="store.select([])" @connect="connect" @node-drag-stop="move"><Background pattern-color="var(--border)" :gap="22"/><Controls/><MiniMap pannable zoomable/><template #node-story="slotProps"><StoryNode v-bind="slotProps"/></template></VueFlow></section><aside class="inspector"><div class="inspector-tabs"><button :class="{active:tab==='inspect'}" @click="tab='inspect'">{{ $t('inspector') }}</button><button :class="{active:tab==='lenses'}" @click="tab='lenses'">{{ $t('storyLenses') }}</button></div><template v-if="tab==='inspect'"><CardInspector v-if="store.selected?.typeId" :item="store.selected" @delete="askDelete"/><div v-else class="inspector-empty">{{ $t('noSelection') }}</div></template><div v-else class="lens-list"><div v-if="!store.lenses.length" class="inspector-empty">{{ $t('noGaps') }}</div><button v-for="lens in store.lenses" :key="lens.id" class="lens-item" @click="focusLens(lens)"><strong>{{ lens.title }}</strong><small>{{ lens.message }}</small></button></div></aside><section class="mobile-list"><p class="mobile-hint">{{ $t('mobileHint') }}</p><input v-model="search" class="search-input" :placeholder="$t('search')"><article v-for="card in store.activeCards.filter(matches).sort((a,b)=>a.typeId==='beat'&&b.typeId==='beat'?Number(a.fields.sequence||0)-Number(b.fields.sequence||0):a.title.localeCompare(b.title))" :key="card.id" class="mobile-card" :style="{'--node-color':card.color}" @click="store.select(card.id)"><small>{{ card.typeId }}</small><h3>{{ card.title }}</h3><p>{{ card.body }}</p></article></section></section>
<div v-if="store.selected?.typeId" class="mobile-editor modal-backdrop"><div class="modal"><div class="panel-heading"><h2>{{ store.selected.title }}</h2><button class="icon-button" aria-label="Close editor" @click="store.select([])">×</button></div><CardInspector :item="store.selected" @delete="askDelete"/></div></div>
<div v-if="showExport" class="modal-backdrop" @click.self="showExport=false"><div class="modal"><h2>{{ $t('export') }}</h2><div class="type-list"><button class="type-button" @click="performExport('archive')">{{ $t('archiveFile') }}</button><button class="type-button" @click="performExport('markdown')">{{ $t('markdown') }}</button><button class="type-button" @click="performExport('png')">{{ $t('png') }}</button></div><div class="modal-actions"><button class="button" @click="showExport=false">{{ $t('cancel') }}</button></div></div></div>
<div v-if="showTrash" class="modal-backdrop" @click.self="showTrash=false"><div class="modal"><h2>{{ $t('trash') }}</h2><div v-for="item in trashed" :key="item.id" class="type-button"><span style="flex:1">{{ item.title||item.label||item.id }}</span><button class="button" @click="restore(item)">{{ $t('restore') }}</button></div><div class="modal-actions"><button class="button" @click="showTrash=false">{{ $t('cancel') }}</button></div></div></div>
<div v-if="confirmDelete" class="modal-backdrop"><div class="modal"><h2>{{ $t('delete') }}?</h2><p>This moves {{ confirmDelete.length }} element(s) to recoverable trash. Their connections will be moved with them.</p><div class="modal-actions"><button class="button" @click="confirmDelete=null">{{ $t('cancel') }}</button><button class="button danger" @click="remove">{{ $t('confirm') }}</button></div></div></div></main></template>
