import { defineStore } from 'pinia'
import { computed, ref } from 'vue'
import { createEmptyBundle, LIMITS, nowIso, uuid } from '../constants.js'
import { createExampleBundle, EXAMPLE_PROJECT_TITLE, EXAMPLE_VERSION } from '../data/example.js'
import { deleteProjectBundle, getDb, getPreference, loadProjectBundle, saveProjectBundle, setPreference } from '../services/db.js'

const clone = (value) => JSON.parse(JSON.stringify(value))
const inBounds = (project, x, y) => x >= 0 && y >= 0 && x < project.width && y < project.height

export const useWorkspaceStore = defineStore('workspace', () => {
  const ready = ref(false), projects = ref([]), bundle = ref(null), selection = ref(null), saveState = ref('saved'), theme = ref('basic'), locale = ref('en'), externalRevision = ref(null)
  const activeTool = ref('terrain'), selectedTerrain = ref('stone'), selectedObject = ref('door'), zoom = ref(1), showGrid = ref(true), playerView = ref(false)
  const undoStack = ref([]), redoStack = ref([])
  let channel
  const terrain = computed(() => bundle.value?.chunks.find((chunk) => chunk.layerId === bundle.value.layers.find((layer) => layer.kind === 'terrain')?.id)?.cells || [])
  const visibleObjects = computed(() => (bundle.value?.objects || []).filter((object) => !object.deletedAt && (!playerView.value || !object.hidden)))
  const visibleLabels = computed(() => (bundle.value?.labels || []).filter((label) => !label.deletedAt && (!playerView.value || !label.hidden)))
  const selectedEntity = computed(() => selection.value?.kind === 'object' ? visibleObjects.value.find((item) => item.id === selection.value.id) : selection.value?.kind === 'label' ? visibleLabels.value.find((item) => item.id === selection.value.id) : null)

  async function initialize() {
    theme.value = await getPreference('theme', matchMedia?.('(prefers-color-scheme: dark)').matches ? 'charcoal' : 'basic'); locale.value = await getPreference('locale', navigator.language?.split('-')[0] || 'en'); await refreshProjects()
    if ((await getPreference('exampleVersion', 0)) < EXAMPLE_VERSION && !projects.value.some((project) => project.title === EXAMPLE_PROJECT_TITLE)) { await saveProjectBundle(createExampleBundle()); await setPreference('exampleVersion', EXAMPLE_VERSION); await refreshProjects() }
    if ('BroadcastChannel' in globalThis) { channel = new BroadcastChannel('story-shack-mapworks'); channel.onmessage = ({ data }) => { if (bundle.value?.project.id === data?.projectId && data.revision > bundle.value.project.revision) externalRevision.value = data.revision } }
    ready.value = true
  }
  async function refreshProjects() { const db = await getDb(); projects.value = (await db.getAll('projects')).sort((a,b) => b.updatedAt.localeCompare(a.updatedAt)) }
  async function openProject(id) { bundle.value = await loadProjectBundle(id); selection.value = null; undoStack.value = []; redoStack.value = []; externalRevision.value = null; return bundle.value }
  async function createNewProject(input = {}) { if (projects.value.filter((item) => !item.deletedAt).length >= LIMITS.projects) throw Object.assign(new Error('Map limit reached'), { code: 'limit_reached' }); const next = createEmptyBundle(input); await saveProjectBundle(next); await refreshProjects(); return next.project }
  async function duplicateProject(id) { const source = await loadProjectBundle(id); if (!source) return null; const copy = createEmptyBundle({ title: `${source.project.title} copy`, description: source.project.description, mapType: source.project.mapType, width: source.project.width, height: source.project.height }); copy.chunks[0].cells = [...source.chunks[0].cells]; copy.structures = source.structures.map((item) => ({ ...item, id: uuid(), projectId: copy.project.id, layerId: copy.layers.find((layer) => layer.kind === 'structure').id })); copy.objects = source.objects.map((item) => ({ ...item, id: uuid(), projectId: copy.project.id, layerId: copy.layers.find((layer) => layer.kind === 'objects').id })); copy.labels = source.labels.map((item) => ({ ...item, id: uuid(), projectId: copy.project.id, layerId: copy.layers.find((layer) => layer.kind === 'labels').id })); await saveProjectBundle(copy); await refreshProjects(); return copy.project }
  async function patchProject(id, patch) { const target = await loadProjectBundle(id); if (!target) return false; target.project = { ...target.project, ...patch, revision: target.project.revision + 1, updatedAt: nowIso() }; await saveProjectBundle(target); if (bundle.value?.project.id === id) bundle.value = target; await refreshProjects(); return true }
  async function purgeProject(id) { await deleteProjectBundle(id); if (bundle.value?.project.id === id) bundle.value = null; await refreshProjects() }
  const snapshot = () => clone(bundle.value)
  async function commit(mutator, { remember = true } = {}) { if (!bundle.value) throw Object.assign(new Error('Map not found'), { code: 'not_found' }); if (externalRevision.value > bundle.value.project.revision) throw Object.assign(new Error('This map changed in another tab'), { code: 'version_conflict' }); if (remember) { undoStack.value.push(snapshot()); if (undoStack.value.length > 50) undoStack.value.shift(); redoStack.value = [] } saveState.value = 'saving'; try { await mutator(bundle.value); bundle.value.project.revision += 1; bundle.value.project.updatedAt = nowIso(); await saveProjectBundle(bundle.value); saveState.value = 'saved'; channel?.postMessage({ projectId: bundle.value.project.id, revision: bundle.value.project.revision }); await refreshProjects(); return bundle.value.project.revision } catch (error) { saveState.value = 'failed'; throw error } }
  async function undo() { if (!undoStack.value.length) return; redoStack.value.push(snapshot()); bundle.value = undoStack.value.pop(); await commit(() => {}, { remember: false }) }
  async function redo() { if (!redoStack.value.length) return; undoStack.value.push(snapshot()); bundle.value = redoStack.value.pop(); await commit(() => {}, { remember: false }) }
  async function paintCells(cells, terrainId) { await commit((draft) => { const data = draft.chunks[0].cells; for (const { x, y } of cells) if (inBounds(draft.project, x, y)) data[y * draft.project.width + x] = terrainId }) }
  async function createRooms(rooms) { await commit((draft) => { const data = draft.chunks[0].cells, layer = draft.layers.find((item) => item.kind === 'structure'); for (const room of rooms) { const left=Math.max(0,room.x), top=Math.max(0,room.y), right=Math.min(draft.project.width-1,left+room.width-1), bottom=Math.min(draft.project.height-1,top+room.height-1); for(let y=top;y<=bottom;y++)for(let x=left;x<=right;x++){data[y*draft.project.width+x]=room.terrain||'stone';if(x===left||x===right||y===top||y===bottom){const existing=draft.structures.find(item=>!item.deletedAt&&item.x===x&&item.y===y);if(!existing)draft.structures.push({id:uuid(),projectId:draft.project.id,layerId:layer.id,kind:'wall',x,y,createdAt:nowIso()})}} } }) }
  async function drawWalls(cells) { await commit((draft) => { const layer=draft.layers.find((item)=>item.kind==='structure'); for(const cell of cells) if(inBounds(draft.project,cell.x,cell.y)&&!draft.structures.some(item=>!item.deletedAt&&item.x===cell.x&&item.y===cell.y)) draft.structures.push({id:uuid(),projectId:draft.project.id,layerId:layer.id,kind:cell.kind||'wall',x:cell.x,y:cell.y,createdAt:nowIso()}) }) }
  async function placeObjects(items) { if (visibleObjects.value.length + items.length > LIMITS.objects) throw Object.assign(new Error('Object limit reached'), { code:'limit_reached' }); const created=[]; await commit((draft)=>{const layer=draft.layers.find((item)=>item.kind==='objects');for(const item of items){if(!inBounds(draft.project,item.x,item.y))continue;const object={id:uuid(),projectId:draft.project.id,layerId:layer.id,assetId:item.assetId,x:item.x,y:item.y,rotation:item.rotation||0,scale:item.scale||1,hidden:Boolean(item.hidden),createdAt:nowIso(),updatedAt:nowIso(),deletedAt:null};draft.objects.push(object);created.push(object)}}); selection.value=created.length?{kind:'object',id:created.at(-1).id}:null;return created }
  async function addLabels(items) { if(visibleLabels.value.length+items.length>LIMITS.labels)throw Object.assign(new Error('Label limit reached'),{code:'limit_reached'});const created=[];await commit((draft)=>{const layer=draft.layers.find((item)=>item.kind==='labels');for(const item of items){const label={id:uuid(),projectId:draft.project.id,layerId:layer.id,text:String(item.text||'Map label').slice(0,200),x:item.x,y:item.y,size:item.size||'medium',hidden:Boolean(item.hidden),createdAt:nowIso(),updatedAt:nowIso(),deletedAt:null};draft.labels.push(label);created.push(label)}});selection.value=created.length?{kind:'label',id:created.at(-1).id}:null;return created }
  async function updateEntity(patch) { const selected=selectedEntity.value;if(!selected)return;await commit(()=>Object.assign(selected,patch,{updatedAt:nowIso()})) }
  async function eraseAt(x,y) { await commit((draft)=>{for(const list of [draft.objects,draft.labels,draft.structures])for(const item of list)if(!item.deletedAt&&item.x===x&&item.y===y)item.deletedAt=nowIso();draft.chunks[0].cells[y*draft.project.width+x]=draft.project.mapType==='dungeon'?'dungeon':'grass'});selection.value=null }
  async function deleteSelection() { const selected=selectedEntity.value;if(!selected)return;await commit(()=>{selected.deletedAt=nowIso()});selection.value=null }
  async function toggleLayer(id) { await commit((draft)=>{const layer=draft.layers.find((item)=>item.id===id);if(layer)layer.visible=!layer.visible}) }
  async function setTheme(value){theme.value=value;await setPreference('theme',value)} async function setLocale(value){locale.value=value;await setPreference('locale',value)}
  function dispose(){channel?.close()}
  return { ready,projects,bundle,selection,saveState,theme,locale,externalRevision,activeTool,selectedTerrain,selectedObject,zoom,showGrid,playerView,undoStack,redoStack,terrain,visibleObjects,visibleLabels,selectedEntity,initialize,refreshProjects,openProject,createNewProject,duplicateProject,patchProject,purgeProject,commit,undo,redo,paintCells,createRooms,drawWalls,placeObjects,addLabels,updateEntity,eraseAt,deleteSelection,toggleLayer,setTheme,setLocale,dispose }
})
