import { defineStore } from 'pinia'
import { computed, ref } from 'vue'
import { createEmptyBundle, getContentBounds, getMapFrame, LABEL_COLORS, LABEL_FONTS, LABEL_SIZES, LIMITS, LINE_STYLES, migrateBundleToSparse, nowIso, SCHEMA_VERSION, setTerrainCell, setTerrainStyle, terrainEntries, terrainRenderEntries, terrainStyleAt, uuid, WORLD_COORDINATE_LIMIT } from '../constants.js'
import { createExampleBundle, EXAMPLE_PROJECT_TITLE, EXAMPLE_VERSION } from '../data/example.js'
import { deleteProjectBundle, getDb, getPreference, loadProjectBundle, saveProjectBundle, setPreference } from '../services/db.js'
import { createRoomStructure, createTerrainStroke, createWallPath, normalizeRoomStructure, pointInStroke, roomShapePoints } from '../services/mapGeometry.js'

const clone = (value) => JSON.parse(JSON.stringify(value))
const inBounds = (project, x, y) => {const frame=getMapFrame(project);return Number.isFinite(x)&&Number.isFinite(y)&&Math.abs(x)<=WORLD_COORDINATE_LIMIT&&Math.abs(y)<=WORLD_COORDINATE_LIMIT&&x>=frame.x&&x<frame.x+frame.width&&y>=frame.y&&y<frame.y+frame.height}
const CHILD_STORES = ['layers', 'chunks', 'terrainStyles', 'terrainStrokes', 'structures', 'objects', 'labels']

export const useWorkspaceStore = defineStore('workspace', () => {
  const ready = ref(false), projects = ref([]), bundle = ref(null), selection = ref(null), saveState = ref('saved'), theme = ref('basic'), locale = ref('en'), externalRevision = ref(null)
  const activeTool = ref('select'), selectedTerrain = ref('stone'), selectedObject = ref('door'), selectedLineStyle = ref(LINE_STYLES[0].id), lineWidth = ref(LINE_STYLES[0].width), brushSize = ref(5), brushSoftness = ref(100), eraserSoftness = ref(0), brushEdge = ref('natural'), zoom = ref(1), showGrid = ref(true)
  const undoStack = ref([]), redoStack = ref([])
  let channel,commitQueue=Promise.resolve()
  const terrain = computed(() => terrainRenderEntries(bundle.value))
  const terrainStrokes = computed(() => (bundle.value?.terrainStrokes || []).filter((stroke) => !stroke.deletedAt))
  const contentBounds = computed(() => getContentBounds(bundle.value, 2))
  const visibleObjects = computed(() => (bundle.value?.objects || []).filter((object) => !object.deletedAt).sort((a,b)=>(a.zIndex||0)-(b.zIndex||0)))
  const visibleLabels = computed(() => (bundle.value?.labels || []).filter((label) => !label.deletedAt))
  const visibleRooms = computed(() => (bundle.value?.structures || []).filter((item) => !item.deletedAt&&item.kind==='room').sort((first,second)=>(first.zIndex||0)-(second.zIndex||0)))
  const selectedEntity = computed(() => selection.value?.kind === 'object' ? visibleObjects.value.find((item) => item.id === selection.value.id) : selection.value?.kind === 'label' ? visibleLabels.value.find((item) => item.id === selection.value.id) : selection.value?.kind === 'room'?visibleRooms.value.find((item)=>item.id===selection.value.id):null)

  async function initialize() {
    theme.value = await getPreference('theme', matchMedia?.('(prefers-color-scheme: dark)').matches ? 'charcoal' : 'basic'); locale.value = 'en'; await refreshProjects()
    if ((await getPreference('exampleVersion', 0)) < EXAMPLE_VERSION && !projects.value.some((project) => project.title === EXAMPLE_PROJECT_TITLE)) { await saveProjectBundle(createExampleBundle()); await setPreference('exampleVersion', EXAMPLE_VERSION); await refreshProjects() }
    if ('BroadcastChannel' in globalThis) { channel = new BroadcastChannel('story-shack-observatory'); channel.onmessage = ({ data }) => { if (bundle.value?.project.id === data?.projectId && data.revision > bundle.value.project.revision) externalRevision.value = data.revision } }
    ready.value = true
  }
  async function refreshProjects() { const db = await getDb(); projects.value = (await db.getAll('projects')).sort((a,b) => b.updatedAt.localeCompare(a.updatedAt)) }
  function refreshCurrentProjectSummary() { const project=clone(bundle.value.project),index=projects.value.findIndex((item)=>item.id===project.id);if(index>=0)projects.value.splice(index,1);projects.value.unshift(project) }
  async function openProject(id) { bundle.value = await loadProjectBundle(id); if (bundle.value?.project.schemaVersion < SCHEMA_VERSION) { migrateBundleToSparse(bundle.value); await saveProjectBundle(bundle.value) }for(const room of bundle.value?.structures?.filter((item)=>item.kind==='room')||[])normalizeRoomStructure(room); selection.value = null; undoStack.value = []; redoStack.value = []; externalRevision.value = null; return bundle.value }
  async function createNewProject(input = {}) { if (projects.value.filter((item) => !item.deletedAt).length >= LIMITS.projects) throw Object.assign(new Error('Map limit reached'), { code: 'limit_reached' }); const next = createEmptyBundle(input); await saveProjectBundle(next); await refreshProjects(); return next.project }
  async function duplicateProject(id) { const source = migrateBundleToSparse(await loadProjectBundle(id)); if (!source) return null; const copy = createEmptyBundle({ title: `${source.project.title} copy`, description: source.project.description, mapType: source.project.mapType }); for (const {x,y,terrain} of terrainEntries(source)) { setTerrainCell(copy,x,y,terrain); setTerrainStyle(copy,x,y,terrainStyleAt(source,x,y)) } copy.terrainStrokes=(source.terrainStrokes||[]).map((item)=>({...item,id:uuid(),projectId:copy.project.id,layerId:copy.layers.find((layer)=>layer.kind==='terrain').id}));copy.structures = source.structures.map((item) => ({ ...item, id: uuid(), projectId: copy.project.id, layerId: copy.layers.find((layer) => layer.kind === 'structure').id })); copy.objects = source.objects.map((item) => ({ ...item, id: uuid(), projectId: copy.project.id, layerId: copy.layers.find((layer) => layer.kind === 'objects').id })); copy.labels = source.labels.map((item) => ({ ...item, id: uuid(), projectId: copy.project.id, layerId: copy.layers.find((layer) => layer.kind === 'labels').id })); await saveProjectBundle(copy); await refreshProjects(); return copy.project }
  async function patchProject(id, patch) { const target = await loadProjectBundle(id); if (!target) return false; target.project = { ...target.project, ...patch, revision: target.project.revision + 1, updatedAt: nowIso() }; await saveProjectBundle(target); if (bundle.value?.project.id === id) bundle.value = target; await refreshProjects(); return true }
  async function purgeProject(id) { await deleteProjectBundle(id); if (bundle.value?.project.id === id) bundle.value = null; await refreshProjects() }
  const captureHistory = (stores = CHILD_STORES) => ({
    stores:[...stores],
    before:Object.fromEntries(stores.map((name)=>[name,name==='terrainStrokes'?{mode:'append',length:(bundle.value[name]||[]).length}:{mode:'replace',value:clone(bundle.value[name]||[])}])),
    after:{},
  })
  const finishHistory = (entry) => {
    for(const name of entry.stores){
      const before=entry.before[name]
      entry.after[name]=before.mode==='append'
        ?{mode:'append',length:before.length,appended:clone((bundle.value[name]||[]).slice(before.length))}
        :{mode:'replace',value:clone(bundle.value[name]||[])}
    }
    return entry
  }
  const applyHistory = (entry,side) => {
    for(const name of entry.stores){
      const state=entry[side][name]
      if(state.mode==='append'){
        bundle.value[name].splice(state.length)
        if(side==='after')bundle.value[name].push(...clone(state.appended||[]))
      }else bundle.value[name]=clone(state.value)
    }
  }
  async function performCommit(mutator, { remember = true, stores = null } = {}) { if (!bundle.value) throw Object.assign(new Error('Map not found'), { code: 'not_found' }); if (externalRevision.value > bundle.value.project.revision) throw Object.assign(new Error('This map changed in another tab'), { code: 'version_conflict' }); const changedStores=stores||CHILD_STORES,history=remember?captureHistory(changedStores):null,rollback={project:clone(bundle.value.project),stores:Object.fromEntries(changedStores.map((name)=>[name,clone(bundle.value[name]||[])])),undo:[...undoStack.value],redo:[...redoStack.value]}; saveState.value = 'saving'; try { await mutator(bundle.value); if(history){undoStack.value.push(finishHistory(history));if(undoStack.value.length>50)undoStack.value.shift();redoStack.value=[]} bundle.value.project.revision += 1; bundle.value.project.updatedAt = nowIso(); await saveProjectBundle(bundle.value,changedStores); saveState.value = 'saved'; channel?.postMessage({ projectId:bundle.value.project.id,revision:bundle.value.project.revision });refreshCurrentProjectSummary();return bundle.value.project.revision } catch(error){bundle.value.project=rollback.project;for(const[name,value]of Object.entries(rollback.stores))bundle.value[name]=value;undoStack.value=rollback.undo;redoStack.value=rollback.redo;saveState.value='failed';throw error} }
  function commit(mutator,options={}) { const pending=commitQueue.then(()=>performCommit(mutator,options));commitQueue=pending.catch(()=>{});return pending }
  async function undo() { await commitQueue;if (!undoStack.value.length) return;const entry=undoStack.value.pop();applyHistory(entry,'before');redoStack.value.push(entry);await commit(() => {}, { remember: false,stores:entry.stores }) }
  async function redo() { await commitQueue;if (!redoStack.value.length) return;const entry=redoStack.value.pop();applyHistory(entry,'after');undoStack.value.push(entry);await commit(() => {}, { remember: false,stores:entry.stores }) }
  async function paintRegions(regions) {
    const targets = new Map()
    for (const region of regions) for (const cell of region.cells) if (inBounds(bundle.value.project, cell.x, cell.y)) targets.set(`${cell.x}:${cell.y}`, cell)
    if (terrain.value.length + terrainStrokes.value.reduce((sum,stroke)=>sum+stroke.points.length,0) + targets.size > LIMITS.terrainCells) throw Object.assign(new Error('Painted area limit reached'), { code: 'limit_reached' })
    await commit((draft) => {
      const layer=draft.layers.find((item)=>item.kind==='terrain')
      let order=Math.max(0,...draft.terrainStrokes.map((stroke)=>stroke.order||0));for (const region of regions){const edge=region.edge||'natural',radius=edge==='crisp'?.51:edge==='wild'?.82:.68,points=region.cells.filter(({x,y})=>inBounds(draft.project,x,y)).map(({x,y})=>({x:x+.5,y:y+.5}));if(points.length)draft.terrainStrokes.push(createTerrainStroke(draft.project,layer.id,{terrain:region.terrain,edge,radius,points,discrete:true,order:++order}))}
    }, { stores:['terrainStrokes'] })
  }
  async function paintCells(cells, terrainId, edge='natural') { return paintRegions([{ terrain: terrainId, edge, cells }]) }
  async function paintStrokes(inputs){const pointCount=inputs.reduce((sum,input)=>sum+(input.points?.length||0),0);if(terrainStrokes.value.reduce((sum,stroke)=>sum+stroke.points.length,0)+pointCount>LIMITS.terrainCells)throw Object.assign(new Error('Painted area limit reached'),{code:'limit_reached'});const created=[];await commit((draft)=>{const layer=draft.layers.find((item)=>item.kind==='terrain');let order=Math.max(0,...draft.terrainStrokes.map((stroke)=>stroke.order||0));for(const input of inputs){const stroke=createTerrainStroke(draft.project,layer.id,{...input,order:++order});if(stroke.points.length){draft.terrainStrokes.push(stroke);created.push(stroke)}}},{stores:['terrainStrokes']});return created}
  async function paintStroke(input){return(await paintStrokes([input]))[0]}
  async function eraseStroke(input){let created;await commit((draft)=>{const layer=draft.layers.find((item)=>item.kind==='terrain'),order=Math.max(0,...draft.terrainStrokes.map((stroke)=>stroke.order||0))+1;created=createTerrainStroke(draft.project,layer.id,{...input,mode:'erase',order});if(!created.points.length)return;draft.terrainStrokes.push(created);for(const item of draft.objects)if(!item.deletedAt&&pointInStroke(created,{x:item.x+.5,y:item.y+.5}))item.deletedAt=nowIso();for(const item of draft.labels)if(!item.deletedAt&&pointInStroke(created,{x:item.x+.5,y:item.y+.5}))item.deletedAt=nowIso();for(const item of draft.structures)if(!item.deletedAt&&(item.points||[item]).some((point)=>pointInStroke(created,{x:(point.x??0)+(item.points?0:.5),y:(point.y??0)+(item.points?0:.5)})))item.deletedAt=nowIso()},{stores:['terrainStrokes','objects','labels','structures']});selection.value=null;return created}
  async function createRooms(rooms) { const created=[];await commit((draft) => { const layer = draft.layers.find((item)=>item.kind==='structure');let zIndex=Math.max(0,...draft.structures.filter((item)=>!item.deletedAt).map((item)=>item.zIndex||0));for(const room of rooms){const next={...createRoomStructure(draft.project,layer.id,room),zIndex:room.zIndex??++zIndex};draft.structures.push(next);created.push(next)} }, { stores:['structures'] });selection.value=created.length?{kind:'room',id:created.at(-1).id}:null;return created }
  async function drawWallPaths(paths){const created=[];await commit((draft)=>{const layer=draft.layers.find((item)=>item.kind==='structure');let zIndex=Math.max(0,...draft.structures.filter((item)=>!item.deletedAt).map((item)=>item.zIndex||0));for(const input of paths){const next={...createWallPath(draft.project,layer.id,input),zIndex:input.zIndex??++zIndex};if(next.points.length>1){draft.structures.push(next);created.push(next)}}},{stores:['structures']});return created}
  async function drawWalls(cells) { const points=cells.filter(({x,y})=>inBounds(bundle.value.project,x,y)).map(({x,y})=>({x:x+.5,y:y+.5}));return drawWallPaths([{points}]) }
  async function placeObjects(items) { if ((bundle.value?.objects||[]).filter((item)=>!item.deletedAt).length + items.length > LIMITS.objects) throw Object.assign(new Error('Object limit reached'), { code:'limit_reached' }); const created=[]; await commit((draft)=>{const layer=draft.layers.find((item)=>item.kind==='objects');let zIndex=Math.max(0,...draft.objects.map((item)=>item.zIndex||0));for(const item of items){if(!inBounds(draft.project,item.x,item.y))continue;const object={id:uuid(),projectId:draft.project.id,layerId:layer.id,assetId:item.assetId,x:item.x,y:item.y,rotation:item.rotation||0,scale:item.scale||1,zIndex:item.zIndex??++zIndex,createdAt:nowIso(),updatedAt:nowIso(),deletedAt:null};draft.objects.push(object);created.push(object)}},{stores:['objects']}); selection.value=created.length?{kind:'object',id:created.at(-1).id}:null;return created }
  async function addLabels(items) { if((bundle.value?.labels||[]).filter((item)=>!item.deletedAt).length+items.length>LIMITS.labels)throw Object.assign(new Error('Label limit reached'),{code:'limit_reached'});const created=[];await commit((draft)=>{const layer=draft.layers.find((item)=>item.kind==='labels');for(const item of items){const label={id:uuid(),projectId:draft.project.id,layerId:layer.id,text:String(item.text||'Map label').slice(0,200),x:item.x,y:item.y,boxWidth:Number.isFinite(item.boxWidth)?Math.max(1,item.boxWidth):null,boxHeight:Number.isFinite(item.boxHeight)?Math.max(1,item.boxHeight):null,rotation:Number.isFinite(item.rotation)?item.rotation:0,fontSize:Number.isFinite(item.fontSize)?Math.max(.35,Math.min(8,item.fontSize)):null,size:LABEL_SIZES.some(({id})=>id===item.size)?item.size:'medium',font:LABEL_FONTS.some(({id})=>id===item.font)?item.font:'sans',color:LABEL_COLORS.some(({id})=>id===item.color)||/^#[0-9a-f]{6}$/i.test(item.color||'')?item.color:'light',bold:Boolean(item.bold),createdAt:nowIso(),updatedAt:nowIso(),deletedAt:null};draft.labels.push(label);created.push(label)}},{stores:['labels']});selection.value=created.length?{kind:'label',id:created.at(-1).id}:null;return created }
  async function updateEntity(patch) { const selected=selectedEntity.value;if(!selected)return;const storeName=selection.value.kind==='object'?'objects':selection.value.kind==='room'?'structures':'labels';await commit(()=>{Object.assign(selected,patch,{updatedAt:nowIso()});if(selection.value.kind==='room')selected.points=roomShapePoints(selected)},{stores:[storeName]}) }
  async function bringSelectionToFront(){const selected=selectedEntity.value,kind=selection.value?.kind;if(!selected||!['object','room'].includes(kind))return;const storeName=kind==='object'?'objects':'structures';await commit((draft)=>{selected.zIndex=Math.max(0,...draft[storeName].filter((item)=>!item.deletedAt).map((item)=>item.zIndex||0))+1;selected.updatedAt=nowIso()},{stores:[storeName]})}
  async function eraseCells(cells) { const targets=new Set(cells.map(({x,y})=>`${x}:${y}`));await commit((draft)=>{const layer=draft.layers.find((item)=>item.kind==='terrain'),points=cells.map(({x,y})=>({x:x+.5,y:y+.5})),order=Math.max(0,...draft.terrainStrokes.map((stroke)=>stroke.order||0))+1;draft.terrainStrokes.push(createTerrainStroke(draft.project,layer.id,{mode:'erase',radius:.51,edge:'crisp',points,discrete:true,order}));for(const list of [draft.objects,draft.labels,draft.structures])for(const item of list)if(!item.deletedAt&&Number.isFinite(item.x)&&targets.has(`${item.x}:${item.y}`))item.deletedAt=nowIso();for(const {x,y} of cells)setTerrainCell(draft,x,y,null)},{stores:['chunks','terrainStyles','terrainStrokes','objects','labels','structures']});selection.value=null }
  async function eraseAt(x,y) { return eraseCells([{x,y}]) }
  async function deleteSelection() { const selected=selectedEntity.value;if(!selected)return;const storeName=selection.value.kind==='object'?'objects':selection.value.kind==='room'?'structures':'labels';await commit(()=>{selected.deletedAt=nowIso()},{stores:[storeName]});selection.value=null }
  async function toggleLayer(id) { await commit((draft)=>{const layer=draft.layers.find((item)=>item.id===id);if(layer)layer.visible=!layer.visible},{stores:['layers']}) }
  async function setTheme(value){theme.value=value;await setPreference('theme',value)} async function setLocale(value){locale.value=value;await setPreference('locale',value)}
  function dispose(){channel?.close()}
  return { ready,projects,bundle,selection,saveState,theme,locale,externalRevision,activeTool,selectedTerrain,selectedObject,selectedLineStyle,lineWidth,brushSize,brushSoftness,eraserSoftness,brushEdge,zoom,showGrid,undoStack,redoStack,terrain,terrainStrokes,contentBounds,visibleObjects,visibleLabels,visibleRooms,selectedEntity,initialize,refreshProjects,openProject,createNewProject,duplicateProject,patchProject,purgeProject,commit,undo,redo,paintRegions,paintCells,paintStrokes,paintStroke,eraseStroke,createRooms,drawWallPaths,drawWalls,placeObjects,addLabels,updateEntity,bringSelectionToFront,eraseCells,eraseAt,deleteSelection,toggleLayer,setTheme,setLocale,dispose }
})
