import { beforeEach,describe,expect,it } from 'vitest'
import { createEmptyBundle, setTerrainCell, setTerrainStyle, terrainAt, terrainStyleAt } from '../../src/constants.js'
import { loadProjectBundle,resetDatabaseForTests,saveProjectBundle } from '../../src/services/db.js'
beforeEach(()=>resetDatabaseForTests())
describe('map persistence',()=>{
  it('round trips signed sparse chunks, continuous strokes, and semantic layers atomically',async()=>{const bundle=createEmptyBundle({title:'Test map'});setTerrainCell(bundle,-3,4,'deep-water');setTerrainStyle(bundle,-3,4,'wild');bundle.terrainStrokes.push({id:crypto.randomUUID(),projectId:bundle.project.id,layerId:bundle.layers[0].id,kind:'terrain-stroke',terrain:'grass',mode:'paint',radius:1,order:1,points:[{x:.25,y:.75}],bounds:{minX:-.75,minY:-.25,maxX:1.25,maxY:1.75}});bundle.objects.push({id:crypto.randomUUID(),projectId:bundle.project.id,layerId:bundle.layers[2].id,assetId:'chest',x:3,y:4});await saveProjectBundle(bundle);const loaded=await loadProjectBundle(bundle.project.id);expect(loaded.project.title).toBe('Test map');expect(terrainAt(loaded,-3,4)).toBe('deep-water');expect(terrainStyleAt(loaded,-3,4)).toBe('wild');expect(loaded.terrainStrokes[0].points[0]).toEqual({x:.25,y:.75});expect(loaded.objects[0].assetId).toBe('chest')})

  it('preserves terrain painter order across reloads',async()=>{const bundle=createEmptyBundle({title:'Layer order'});for(const [order,terrain] of [[3,'grass'],[1,'deep-water'],[2,'sand']])bundle.terrainStrokes.push({id:crypto.randomUUID(),projectId:bundle.project.id,layerId:bundle.layers[0].id,kind:'terrain-stroke',terrain,mode:'paint',radius:1,order,points:[{x:0,y:0}],bounds:{minX:-1,minY:-1,maxX:1,maxY:1}});await saveProjectBundle(bundle);const loaded=await loadProjectBundle(bundle.project.id);expect(loaded.terrainStrokes.map((stroke)=>stroke.terrain)).toEqual(['deep-water','sand','grass'])})
  it('updates selected stores without rewriting unrelated map data',async()=>{const bundle=createEmptyBundle({title:'Partial save'}),object={id:crypto.randomUUID(),projectId:bundle.project.id,layerId:bundle.layers[2].id,assetId:'chest',x:3,y:4};bundle.objects.push(object);setTerrainCell(bundle,0,0,'grass');await saveProjectBundle(bundle);setTerrainCell(bundle,1,0,'sand');bundle.objects=[];bundle.project.revision++;await saveProjectBundle(bundle,['chunks']);const loaded=await loadProjectBundle(bundle.project.id);expect(terrainAt(loaded,1,0)).toBe('sand');expect(loaded.objects).toEqual([object])})
})
