import { describe,expect,it,vi } from 'vitest'
import { webMcpTestApi } from '../../src/services/webMcp.js'
const projectId='11111111-1111-4111-8111-111111111111',operationId='22222222-2222-4222-8222-222222222222'
function fakeStore(){return{bundle:{project:{id:projectId,title:'Test',mapType:'dungeon',width:12,height:10,revision:3},layers:[],chunks:[{cells:Array(120).fill('stone')}],structures:[],objects:[],labels:[]},terrain:Array(120).fill('stone'),selection:null,visibleObjects:[],visibleLabels:[],paintCells:vi.fn(async()=>{}),createRooms:vi.fn(async()=>{}),drawWalls:vi.fn(async()=>{}),placeObjects:vi.fn(async(items)=>items.map((item,index)=>({id:`object-${index}`,...item}))),addLabels:vi.fn(async()=>[]),commit:vi.fn(async(fn)=>fn({objects:[],labels:[],structures:[]}))}}
describe('Mapworks WebMCP',()=>{
it('discovers and disposes a fake-browser scope',async()=>{const registered=[];Object.defineProperty(document,'modelContext',{value:{registerTool:vi.fn(async(tool)=>registered.push(tool.name))},configurable:true});const dispose=webMcpTestApi.registerScope('test-scope',[{name:'test_tool',title:'Test',description:'Test',inputSchema:{type:'object',additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>({status:'ok'})}]);await new Promise((resolve)=>setTimeout(resolve));expect(registered).toEqual(['test_tool']);dispose();expect(webMcpTestApi.supported()).toBe(true);delete document.modelContext})
it('rejects additional input and stale revisions',async()=>{const store=fakeStore(),entry=webMcpTestApi.projectTools(store).find((item)=>item.name==='paint_map_terrain');const invalid=await webMcpTestApi.runTool(entry,{operation_id:operationId,expected_revision:3,terrain:'stone',cells:[{x:1,y:1}],extra:true});expect(invalid.error_code).toBe('invalid_input');const stale=await webMcpTestApi.runTool(entry,{operation_id:operationId,expected_revision:2,terrain:'stone',cells:[{x:1,y:1}]});expect(stale.error_code).toBe('version_conflict')})
it('places a semantic batch once and replays its result',async()=>{const store=fakeStore(),entry=webMcpTestApi.projectTools(store).find((item)=>item.name==='place_map_objects'),input={operation_id:operationId,expected_revision:3,objects:[{assetId:'chest',x:2,y:3},{assetId:'door',x:4,y:5}]};const first=await webMcpTestApi.runTool(entry,input),second=await webMcpTestApi.runTool(entry,input);expect(first.status).toBe('ok');expect(second).toEqual(first);expect(store.placeObjects).toHaveBeenCalledTimes(1)})
it('binds element removal to a human preview',async()=>{const store=fakeStore(),entry=webMcpTestApi.projectTools(store).find((item)=>item.name==='delete_map_elements');vi.spyOn(window,'confirm').mockReturnValue(true);const previewInput={operation_id:operationId,expected_revision:3,ids:['33333333-3333-4333-8333-333333333333'],risk:{preview:true}},preview=await webMcpTestApi.runTool(entry,previewInput);expect(preview.status).toBe('preview');const commit=await webMcpTestApi.runTool(entry,{...previewInput,risk:{preview:false,preview_token:preview.data.preview_token}});expect(commit.status).toBe('ok');expect(store.commit).toHaveBeenCalledOnce()})
})
