import { describe,expect,it,vi } from 'vitest'
import { webMcpTestApi } from '../../src/services/webMcp.js'

const projectId='11111111-1111-4111-8111-111111111111', operationId='22222222-2222-4222-8222-222222222222'
function fakeStore(){const store={bundle:{project:{id:projectId,title:'Test',premise:'A premise',revision:3},cards:[],relationships:[],groups:[],cardTypes:[],media:[]},selection:[],activeCards:[],activeRelationships:[],activeGroups:[],lenses:[],addCards:vi.fn(async inputs=>inputs.map((x,index)=>({id:`card-${index}`,...x}))),deleteElements:vi.fn(async()=>{}),arrange:vi.fn(async()=>{}),updateCards:vi.fn(),connectCards:vi.fn(),manageGroups:vi.fn(),manageMedia:vi.fn()};return store}
describe('WebMCP contract',()=>{
  it('discovers and disposes a fake-browser scope',async()=>{const registered=[];Object.defineProperty(document,'modelContext',{value:{registerTool:vi.fn(async tool=>registered.push(tool.name))},configurable:true});const dispose=webMcpTestApi.registerScope('test-scope',[{name:'test_tool',title:'Test',description:'Test',inputSchema:{type:'object',additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>({status:'ok'})}]);await new Promise(resolve=>setTimeout(resolve));expect(registered).toEqual(['test_tool']);dispose();expect(webMcpTestApi.supported()).toBe(true);delete document.modelContext})
  it('rejects additional input and stale revisions',async()=>{const store=fakeStore(),tool=webMcpTestApi.projectTools(store).find(x=>x.name==='create_story_cards');const invalid=await webMcpTestApi.runTool(tool,{operation_id:operationId,expected_revision:3,cards:[{typeId:'note',title:'X'}],extra:true});expect(invalid.error_code).toBe('invalid_input');const stale=await webMcpTestApi.runTool(tool,{operation_id:operationId,expected_revision:2,cards:[{typeId:'note',title:'X'}]});expect(stale.error_code).toBe('version_conflict')})
  it('creates a batch once and replays the cached result',async()=>{const store=fakeStore(),tool=webMcpTestApi.projectTools(store).find(x=>x.name==='create_story_cards'),input={operation_id:operationId,expected_revision:3,cards:[{typeId:'note',title:'One'},{typeId:'beat',title:'Two'}]};const first=await webMcpTestApi.runTool(tool,input),second=await webMcpTestApi.runTool(tool,input);expect(first.status).toBe('ok');expect(second).toEqual(first);expect(store.addCards).toHaveBeenCalledTimes(1)})
  it('binds recoverable deletion to human preview',async()=>{const store=fakeStore(),tool=webMcpTestApi.projectTools(store).find(x=>x.name==='delete_story_elements');vi.spyOn(window,'confirm').mockReturnValue(true);const previewInput={operation_id:operationId,expected_revision:3,ids:['33333333-3333-4333-8333-333333333333'],risk:{preview:true}},preview=await webMcpTestApi.runTool(tool,previewInput);expect(preview.status).toBe('preview');const commit=await webMcpTestApi.runTool(tool,{...previewInput,risk:{preview:false,preview_token:preview.data.preview_token}});expect(commit.status).toBe('ok');expect(store.deleteElements).toHaveBeenCalledOnce()})
})
